### ISSUE TITLE
Installing “atom-quokka@1.0.19” Failed in Atom IDE

### ISSUE THREAD

**Issue by adefirmanf** [wallabyjs/quokka#100]
### Issue description or question

I can't install atom in quokka using a Package manager.

### Atom console output / Node console output
```
> quokka-atom@1.0.19 install /tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/node_modules/atom-quokka/node_modules/quokka-atom
> node script/install.js

/tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr
└── (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/node_modules/atom-quokka/node_modules/quokka-atom/script/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/package.json'
npm WARN apm-install-dir-11795-16065-ih48jv.ixcyd2huxr No description
npm WARN apm-install-dir-11795-16065-ih48jv.ixcyd2huxr No repository field.
npm WARN apm-install-dir-11795-16065-ih48jv.ixcyd2huxr No README data
npm WARN apm-install-dir-11795-16065-ih48jv.ixcyd2huxr No license field.
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/tmp/d-11795-16065-4atnpu.j70a2d42t9/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! quokka-atom@1.0.19 install: `node script/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quokka-atom@1.0.19 install script 'node script/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quokka-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quokka-atom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quokka-atom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/npm-debug.log
npm ERR! code 1
```

### Code editor version

Atom 

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
Can you install it directly from the editor (via `Settings - Install`)?

**Comment by adefirmanf** [comment]
Yap, it was. But the result is same. 

![screenshot from 2017-10-05 15-30-15](https://user-images.githubusercontent.com/23324722/31217741-3b1589f6-a9e2-11e7-89f4-169380062ca7.png)

**Comment by ArtemGovorov** [comment]
Are you behind some corporate proxy?

The error mentions the folder like`/tmp/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/node_modules/atom-quokka/node_modules/quokka-atom/`, could you please take a look inside the folder to see what is in there and inside the `/script` subfolder?

**Comment by adefirmanf** [comment]
Yeah, I'm running behind a corporate proxy. When I look inside the folder `/tmp` the result is blank. Nothing folder like `/apm-install-dir-11795-16065-ih48jv.ixcyd2huxr/`

I don't know why this happened. Anyway, I'm running Atom inside root access.

**Comment by ArtemGovorov** [comment]
> Yeah, I'm running behind a corporate proxy.

Then it looks like you have this issue: https://github.com/wallabyjs/atom-quokka/issues/1, please use the solution described there.
