### ISSUE TITLE
Something about react not being included?

### ISSUE THREAD

**Issue by oshalygin** [wallabyjs/quokka#122]
### Issue description or question
Getting this error on this project and Quokka basically doesn't work at all.

```
​​Failed to run compilers on quokka.js, Error: Couldn't find preset "react" relative to directory "."​​
​​    at /Users/oshalygin/dev/get-recs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19​​
​​    at Array.map (<anonymous>)​​
```
### Sample code

Here is babelrc, note there's no `wallaby` in this project.
```
{
  "presets": ["latest", "stage-1"],
  "env": {
    "development": {
      "plugins": [
        "transform-object-rest-spread",
        "syntax-trailing-function-commas",
        [
          "transform-runtime",
          {
            "polyfill": false,
            "regenerator": true
          }
        ]
      ]
    },
    "test": {
      "plugins": [
        [
          "transform-runtime",
          {
            "polyfill": false,
            "regenerator": true
          }
        ]
      ]
    },
    "production": {
      "plugins": [
        "transform-object-rest-spread",
        "syntax-trailing-function-commas",
        [
          "transform-runtime",
          {
            "polyfill": false,
            "regenerator": true
          }
        ]
      ]
    }
  }
}

```

Here is package.json:
I know this looks wonky with all of the wildcard flags and so on, its a work in progress I didn't start this :)

```
{
  "name": "recs",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "NODE_ENV=production babel-node ./application.js",
    "start-dev": "babel-watch ./application.js"
  },
  "engines": {
    "node": "8.5.0"
  },
  "dependencies": {
    "@angular/common": "^4.3.5",
    "@angular/core": "^4.3.5",
    "@angular/http": "^4.3.5",
    "@angular/platform-browser": "^4.3.5",
    "@sendgrid/mail": "^6.1.4",
    "angular2-jwt": "^0.2.3",
    "babel-cli": "6.24.1",
    "babel-core": "6.24.1",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.0.0",
    "babel-plugin-syntax-trailing-function-commas": "6.22.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-object-rest-spread": "6.23.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-polyfill": "6.23.0",
    "babel-preset-latest": "6.24.1",
    "babel-preset-stage-1": "6.24.1",
    "babel-regenerator-runtime": "6.5.0",
    "babel-runtime": "6.23.0",
    "babel-template": "6.24.1",
    "babel-types": "6.24.1",
    "babel-watch": "^2.0.7",
    "body-parser": "^1.13.3",
    "bootstrap-social": "^5.1.1",
    "connect-pg-simple": "^4.2.1",
    "connect-session-sequelize": "^4.1.0",
    "cookie-parser": "^1.3.5",
    "debug": "~2.2.0",
    "dialog": "^0.3.1",
    "ejs": "^2.5.7",
    "es6": "0.0.7",
    "es6-shim": "^0.35.3",
    "eslint": "3.19.0",
    "eslint-config-prettier": "2.3.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-watch": "3.1.0",
    "express": "~4.13.1",
    "express-session": "^1.15.5",
    "express-validator": "^4.1.1",
    "express-winston": "2.4.0",
    "fb": "^2.0.0",
    "google-places": "0.0.2",
    "morgan": "~1.6.1",
    "nodemailer": "^4.4.0",
    "passport": "^0.4.0",
    "passport-facebook": "^2.1.1",
    "pg": "^7.3.0",
    "pg-hstore": "^2.3.2",
    "pm2": "^2.7.2",
    "prettier": "1.5.3",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.3",
    "sequelize": "^4.22.4",
    "sequelize-models": "^1.3.1",
    "serve-favicon": "~2.3.0",
    "slug": "^0.9.1",
    "unirest": "^0.5.1",
    "universal-analytics": "^0.4.15",
    "util": "^0.10.3",
    "uuid": "^3.1.0",
    "winston": "2.4.0",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.24.1"
  }
}

```
### Quokka.js Console Output

```
​​Failed to run compilers on quokka.js, Error: Couldn't find preset "react" relative to directory "."​​
​​    at /Users/oshalygin/dev/get-recs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19​​
​​    at Array.map (<anonymous>)​​
```

### Code editor version

Visual Studio Code v1.18.1

### OS name and version

OSX High Sierra
Quokka Pro

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue, must be missing some details. Created this repo with your config files https://github.com/ArtemGovorov/quokka-122, creating a new Quokka scratch file in it, and everything is working:

<img width="502" alt="screen shot 2017-11-27 at 4 22 18 pm" src="https://user-images.githubusercontent.com/979966/33253501-73c7b55e-d38f-11e7-91ce-15f67272b49f.png">

Please try the repo to see if it's working for you, and if it is, please add the bits I'm missing to reproduce the issue.

**Comment by ArtemGovorov** [comment]
Also your project doesn't even seem to use `react`. So one thing to check would be your `~/.quokka/config.json` file, to see if you don't have `react` preset configured there.

**Comment by smcenlly** [comment]
Closing this issue due to age and inactivity.
