### ISSUE TITLE
cant install quokka on atom

### ISSUE THREAD

**Issue by PinkyRabbit** [wallabyjs/quokka#147]
### Issue description or question
I seen quokka on youtube screencast and that looks awesome powerfool thing. But... when I want to install in on Atom that was runned under sudo I got an error. 
```
> quokka-atom@1.0.43 install /tmp/apm-install-dir-118016-21623-duelps.o690vbo6r/node_modules/atom-quokka/node_modules/quokka-atom
> node script/install.js

/tmp/apm-install-dir-118016-21623-duelps.o690vbo6r
└── (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118016-21623-duelps.o690vbo6r/node_modules/atom-quokka/node_modules/quokka-atom/script/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118016-21623-duelps.o690vbo6r/package.json'
npm WARN apm-install-dir-118016-21623-duelps.o690vbo6r No description
npm WARN apm-install-dir-118016-21623-duelps.o690vbo6r No repository field.
npm WARN apm-install-dir-118016-21623-duelps.o690vbo6r No README data
npm WARN apm-install-dir-118016-21623-duelps.o690vbo6r No license field.
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/usesa/.atom/.apm/.apmrc" "--userconfig" "/home/usesa/.atom/.apmrc" "install" "/tmp/d-118016-21623-obw0nf.m1ygjsjor/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! quokka-atom@1.0.43 install: `node script/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quokka-atom@1.0.43 install script 'node script/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quokka-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quokka-atom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quokka-atom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118016-21623-duelps.o690vbo6r/npm-debug.log
npm ERR! code 1
```
And there is no such file like `/tmp/apm-install-dir-118016-21623-duelps.o690vbo6r/npm-debug.log`
### Code editor version
Atom v1.22.1 x64

### OS name and version
Linux 16.04

**Comment by ArtemGovorov** [comment]
Unfortunately we can't reproduce the error in our testing environment.

Please try re-installing the package again, if you were installing it from UI - try installing it from command line using `apm`, or the other way around. 

If you are behind some proxy, try the solution from here https://github.com/wallabyjs/atom-quokka/issues/1

**Comment by PinkyRabbit** [comment]
Still error even with `apm` and still no log file
```
usesa@pinkya-spot:~$ sudo apm install atom-quokka
Installing atom-quokka to /home/usesa/.atom/packages ✗

> quokka-atom@1.0.43 install /tmp/apm-install-dir-118016-25603-7wi3im.csi14kuik9/node_modules/atom-quokka/node_modules/quokka-atom
> node script/install.js

/tmp/apm-install-dir-118016-25603-7wi3im.csi14kuik9
└── (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118016-25603-7wi3im.csi14kuik9/node_modules/atom-quokka/node_modules/quokka-atom/script/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118016-25603-7wi3im.csi14kuik9/package.json'
npm WARN apm-install-dir-118016-25603-7wi3im.csi14kuik9 No description
npm WARN apm-install-dir-118016-25603-7wi3im.csi14kuik9 No repository field.
npm WARN apm-install-dir-118016-25603-7wi3im.csi14kuik9 No README data
npm WARN apm-install-dir-118016-25603-7wi3im.csi14kuik9 No license field.
npm ERR! Linux 4.13.0-26-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/usesa/.atom/.apm/.apmrc" "--userconfig" "/home/usesa/.atom/.apmrc" "install" "/tmp/d-118016-25603-ts088v.5l2nijm7vi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! quokka-atom@1.0.43 install: `node script/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quokka-atom@1.0.43 install script 'node script/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quokka-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quokka-atom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quokka-atom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118016-25603-7wi3im.csi14kuik9/npm-debug.log
npm ERR! code 1
```

**Comment by ArtemGovorov** [comment]
Try running `apm install atom-quokka` without `sudo`.

**Comment by PinkyRabbit** [comment]
Done. Im lame sorry...
