### ISSUE TITLE
Quokka console output contains many "Zero Width Spaces"

### ISSUE THREAD

**Issue by dallonf** [wallabyjs/quokka#151]
### Issue description or question

When copying Quokka output from the VS Code output console, it contains many Unicode 8203 "Zero Width Space" characters, which makes it extremely cumbersome to paste output into other places. 

This may be a VS Code issue, but I've only observed it with Quokka so I figured I'd start here.

### Sample code

Initially:

```javascript
const myString = 'abcd';
console.log(myString); // abcd
console.log([...myString]); // [ 'a', 'b', 'c', 'd' ]
console.log([...myString].map(c => c.charCodeAt(0))); // [ 97, 98, 99, 100 ]
```

Then if I copy the output from line 2 and paste it into another string literal:

```javascript
const pastedString = '​​​​​abcd​​​​​';
console.log([...pastedString]); // [ '', '', '', '', '', 'a', 'b', 'c', 'd', '', '', '', '', '' ]
console.log([...pastedString].map(c => c.charCodeAt(0))) // [ 8203, 8203, 8203, 8203, 8203, 97, 98, 99, 100, 8203, 8203, 8203, 8203, 8203 ]
```

See also a quick gif:

![quokka-vs-code-8203](https://user-images.githubusercontent.com/346300/35338200-e4b5f49e-00e2-11e8-950f-342a6879f7da.gif)

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.9.3)​​​​

​​​​​abcd​​​​​ at ​​​myString​​​ ​quokka.js:2:0​
​​​​​​​​​​
​​​​​[ 'a', 'b', 'c', 'd' ]​​​​​
  at ​​​[...myString]​​​ ​quokka.js:3:0​

​​​​​[ 97, 98, 99, 100 ]​​​​​ at ​​​[...myString].map(c => c.charCodeAt(0))​​​ ​quokka.js:4:35​
​​​​​​​​​​
​​​​​[ '​', '​', '​', '​', '​', 'a', 'b', 'c', 'd', '​', '​', '​', '​', '​' ]​​​​​
  at ​​​[...pastedString]​​​ ​quokka.js:7:0​
​​​​​​​​​​
​​​​​[ 8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  97,​​​​​
​​​​​  98,​​​​​
​​​​​  99,​​​​​
​​​​​  100,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203,​​​​​
​​​​​  8203 ]​​​​​
  at ​​​[...pastedString].map(c => c.charCodeAt(...​​​ ​quokka.js:8:39​

```

### Code editor version

Visual Studio Code v1.19.2

### OS name and version

macOS 10.12.6

**Comment by ArtemGovorov** [comment]
Unfortunately in VS Code we had to use the grammar with special characters to have the coloured output. We'll need to investigate if there's a better way to highlight the output, but for now it seems to be the only way.

**Comment by dallonf** [comment]
OK, thanks for the input. I'll go make an issue over on the VS Code project and see if maybe it can be fixed on that front.

**Comment by dallonf** [comment]
Ugh, they closed it with a bot. Would you be able to file a more informed issue about which part of the extension API causes this problem?

**Comment by dallonf** [comment]
@ArtemGovorov Since it looks like a longer-term fix could take a while and require more support from VS Code, could there be an extension setting to turn off colored output?

**Comment by nomeyer** [comment]
Hi there, any update on this?

A setting to turn off coloured output like @dallonf suggested would be super helpful – my (personal) workflow leads me to copy/paste `quokka` output way more frequently than using the coloured output, and it's quite painful to work around this.

Thanks

**Comment by ArtemGovorov** [comment]
We just have added VS Code `quokka.colorizeOutput` setting in the latest published extension version. Please use the setting to disable the output colorisation (that should also stop Quokka from emitting zero width spaces).

**Comment by nomeyer** [comment]
@ArtemGovorov Awesome, thank you 🙏 I've updated & can confirm it works 🎉
