### ISSUE TITLE
Activating quokka fails

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/quokka#174]
### Issue description or question
I just tried to open up quokka in VS code and getting below:

```

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Here is the error stack:  Error: Cannot find module './dist/index'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:784)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at exports.activate (/Users/ojkwon/.vscode/extensions/WallabyJs.quokka-vscode-1.0.115/index.js:15:42)
	at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:695:93)
	at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:694:787)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:693:916
```

Uninstalling / reinstalling extension itself doesn't seem work. Any suggestions I can try?

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
It looks like your Quokka installation had been corrupted somehow. Please try
- closing the editor,
- deleting all `/Users/ojkwon/.vscode/extensions/WallabyJs.quokka-vscode-*` files,
- opening the editor and installing the extension.

If it still doesn;t work after performing the steps, please open ``/Users/ojkwon/.vscode/extensions/`, compress the `WallabyJs.quokka-vscode-1.0.115` folder and attach it to the issue.
