### ISSUE TITLE
exception when i try to start 

### ISSUE THREAD

**Issue by maxkvoronin** [wallabyjs/quokka#192]
### Issue description or question
there is exception when i try to start quokka

null
java.lang.NullPointerException
	at java.awt.Container.addImpl(Container.java:1093)
	at java.awt.Container.add(Container.java:973)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.c(ToolWindowContentUi.java:201)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.access$200(ToolWindowContentUi.java:62)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$2.selectionChanged(ToolWindowContentUi.java:170)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy89.selectionChanged(Unknown Source)
	at com.intellij.ui.content.impl.ContentManagerImpl.a(ContentManagerImpl.java:574)
	at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:390)
	at com.intellij.ui.content.impl.ContentManagerImpl$1.run(ContentManagerImpl.java:481)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:497)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:448)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:437)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:515)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:520)
	at com.intellij.ui.content.impl.ContentManagerImpl.b(ContentManagerImpl.java:173)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:150)
	at com.quokka.javascript.QuokkaView.a(Unknown Source)
	at com.quokka.javascript.session.l.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.s(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
![screenshot_1165](https://user-images.githubusercontent.com/38040956/39482061-40c36fd4-4d76-11e8-8661-1faf22a4347a.jpg)

### Code editor version

phpstorm 2018.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please 
- specify what version of Quokka plugin is installed,
- restart your IDE, 
- try starting Quokka and provide an extract from your idea.log (starting from the moment/time when you restarted the IDE and started Quokka). You may open the log file by using `Help - Show Log` menu in the IDE.

**Comment by SeanDez** [comment]
More information:

Specify what version of Quokka plugin is installed,
**Quokka version 1.0.95**

Restart your IDE
**done**

Try starting Quokka and provide an extract from your idea.log (starting from the moment/time when you restarted the IDE and started Quokka). You may open the log file by using Help - Show Log menu in the Phpstorm IDE.

[phpstorm_log_jun_6_2018.txt](https://github.com/wallabyjs/quokka/files/2102394/phpstorm_log_jun_6_2018.txt)

**Comment by smcenlly** [comment]
Closing this issue due to age and inactivity.
