### ISSUE TITLE
Doesn't work in VSCode on Debian GNU/Linux 8 (jessie) 64-bit

### ISSUE THREAD

**Issue by DeylRaytop** [wallabyjs/quokka#250]
### Issue description or question
Hello. Installed from plugin market. It doesn't respond to any actions. Tried to delete/install Quokka/VSCode. Nothing helped.
### Sample code
```
const msg = 'Hey';
console.log(msg);
```

### Quokka.js Console Output

```
log.ts:171   ERR Negative opened editor count for ../../everyday-js/may2018/may24/Untitled-1.js: Error: Negative opened editor count for ../../everyday-js/may2018/may24/Untitled-1.js
    at p.fileClosedInEditor (/home/soulvis/.vscode/extensions/wallabyjs.quokka-vscode-1.0.148/dist/wallaby/client.js:14:4187)
    at /home/soulvis/.vscode/extensions/wallabyjs.quokka-vscode-1.0.148/dist/index.js:5:15851
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:786:954
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
    at e.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:785:159)
    at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
    at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
    at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
    at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
    at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
    at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Code editor version

Version: 1.27.2
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T07:11:15.873Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

### OS name and version
Debian GNU/Linux 8 (jessie) 64-bit

**Comment by DeylRaytop** [comment]
> Could you please share the output from Quokka console ? (the one you have shared looks like it is from Dev Tools console).
> […](#)

Excuse me, Artem, no can do, since it's empty. I also noticed that something is loading, if I delete it, the loading process disappears.
![selection_122](https://user-images.githubusercontent.com/25981778/45583098-a2001e00-b8dd-11e8-9c30-e3d096e6b7d8.png)

**Comment by ArtemGovorov** [comment]
Could you please also install [VS Code insiders](https://code.visualstudio.com/insiders/) with no other extensions, install Quokka there and see if its working (to check if there's may be a conflict with some other installed extensions)?

**Comment by DeylRaytop** [comment]
> * what is your node.js version (result of `node -v` command in your terminal)?

v9.4.0



> Could you please also install [VS Code insiders](https://code.visualstudio.com/insiders/) with no other extensions, install Quokka there and see if its working (to check if there's may be a conflict with some other installed extensions)?

The same errors.
```
log.ts:159  INFO no standard startup: not a new window
console.ts:136 [Extension Host]  [Info]  #1 Quokka.js stopped (at Object.appendLine (/home/soulvis/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.148/dist/index.js:5:7892))
console.ts:136 [Extension Host] TextEditor is closed/disposed (at e._runOnProxy (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:437:262))
t.log @ console.ts:136
console.ts:136 [Extension Host]  [Info]  #2 Quokka.js stopped (at Object.appendLine (/home/soulvis/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.148/dist/index.js:5:7892))
log.ts:171   ERR no adapter found: Error: no adapter found
	at e._withAdapter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:503:117)
	at e.$provideCodeActions (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:507:65)
	at t._doInvokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:628:802)
	at t._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:628:468)
	at t._receiveRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:627:60)
	at t._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:626:126)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:623:784
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:97:910
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:218)
	at a (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:153:703)
	at Socket._socketDataListener (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:153:922)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
mainThreadExtensionService.ts:43 [WallabyJs.quokka-vscode]Negative opened editor count for quokka.js
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
t._doInvokeHandler @ rpcProtocol.ts:435
t._invokeHandler @ rpcProtocol.ts:420
t._receiveRequest @ rpcProtocol.ts:342
t._receiveOneMessage @ rpcProtocol.ts:279
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:44 Error: Negative opened editor count for quokka.js
	at p.fileClosedInEditor (/home/soulvis/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.148/dist/wallaby/client.js:14:4187)
	at /home/soulvis/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.148/dist/index.js:5:15851
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:218)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:576:954
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:218)
	at e.$acceptDocumentsAndEditorsDelta (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:479:898)
	at t._doInvokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:628:802)
	at t._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:628:468)
	at t._receiveRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:627:126)
	at t._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:626:126)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:623:784
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:97:910
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:218)
	at a (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:153:703)
	at Socket._socketDataListener (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:153:922)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
t._doInvokeHandler @ rpcProtocol.ts:435
t._invokeHandler @ rpcProtocol.ts:420
t._receiveRequest @ rpcProtocol.ts:342
t._receiveOneMessage @ rpcProtocol.ts:279
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. We have just published a new version 1.0.149 to address the only possible issue I can see being reported. Please try the latest 1.0.149 extension version and let us know how it goes.

**Comment by ArtemGovorov** [comment]
Unfortunately I'm running out of ideas why Quokka doesn't work in your environment (also without reporting any errors). One last thing I can suggest trying, in your [Quokka config](https://quokkajs.com/docs/configuration.html):
- try specifying an absolute [path to your node binary](https://quokkajs.com/docs/configuration.html#nodejs-version),
- try disabling the `esm` module that Quokka is using by default as described at https://github.com/wallabyjs/quokka/issues/157#issuecomment-364392492.

**Comment by DeylRaytop** [comment]
> * try specifying an absolute [path to your node binary](https://quokkajs.com/docs/configuration.html#nodejs-version),
There it is. Happily, everything works now. Thank you for your time, Artem.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
