### ISSUE TITLE
Can't run any Quokka.js commands

### ISSUE THREAD

**Issue by remy** [wallabyjs/quokka#289]
### Issue description or question

I know this issue has been opened multiple times and resolved via re-installs, but I'm completely failing here!

All the commands I run results in `command "quokka.… not found"

<img width="587" alt="screen shot 2018-11-12 at 12 18 04" src="https://user-images.githubusercontent.com/13700/48347058-07ba1d80-e675-11e8-9cea-4de3dd4aa415.png">

Things I've tried:

- Re-installing the extension from the extensions sidebar
- Disabling and re-enabling
- Closing VC Code, and deleting the `~/.vscode/extensions/wallabyjs.quokka*` directory and re-installing

The output from VS Code devtools isn't particular useful, but I've included it below:

<details><summary><em>output log</em></summary>

```text
 INFO standard startup Object
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Looking for parseable documents...
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Found no documents
notificationsAlerts.ts:40 Error: command 'quokka.createJavaScriptFile' not found
    at t._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3030:36)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3029:885
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:343)
    at l (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:168:855)
    at n.Class.derive.join.r.forEach.G.then.o.(anonymous function) (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:169:45)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:343)
    at l (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:168:855)
    at n.Class.derive.join.r.forEach.G.then.o.(anonymous function) (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:169:45)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._creator._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._creator._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:343)
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:165:343)
    at e.resolveOk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3186:248)
    at t._receiveReply (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266:305)
    at t._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3264:600)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3262:81
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:181:218)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:318:348)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:318:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.error @ notificationService.ts:50
t.onError @ commandsHandler.ts:328
(anonymous) @ commandsHandler.ts:313
m @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_chainedError @ winjs.base.js:1052
n @ winjs.base.js:751
then @ winjs.base.js:1457
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.G.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
e.resolveOk @ lazyPromise.ts:59
t._receiveReply @ rpcProtocol.ts:399
t._receiveOneMessage @ rpcProtocol.ts:298
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594


notificationsAlerts.ts:40 Error: command 'quokka.createJavaScriptFile' not found
    at t._tryExecuteCommand (commandService.ts:57)
    at commandService.ts:50
    at n.Class.derive._oncancel.then (winjs.base.js:1587)
    at t.executeCommand (commandService.ts:50)
    at t.run (actions.ts:220)
    at t.run (actions.ts:268)
    at commandsHandler.ts:309
```
</details>

I'd love to be able to run this extension, so if there's anything else I can provide to help debug, please let me know. Thanks in advance.

### Code editor version

Visual Studio Code v1.28.2 (1.28.2)

### OS name and version

OSX 10.13.6 (17G65)

**Comment by remy** [comment]
I found the debug flag in the source of the extension that this shows some errors in the devtools log:

<img width="1280" alt="screen shot 2018-11-12 at 12 27 57" src="https://user-images.githubusercontent.com/13700/48347554-7c418c00-e676-11e8-8e90-275a7aad1fbe.png">

Not sure quite what it means, but I'll see if I can debug a little further.

**Comment by remy** [comment]
I think I've solved it. It's a bit weird, but here's what I had to do:

1. Disable my VS Live Share extension (it appears in the stack trace above, so possibly related)
2. Close VS Code
3. Delete the Quokka ext directory `~/.vscode/extensions/wallabyjs.quokka*`
4. Open VS Code and install Quokka

At that point the notification about upgrading the extension to pro comes up - which tells me it's all okay again.

I don't have the original ext directory to zip up and upload to provide debugging because I'd been doing it a number of times, but the one big difference I had was the VS Live Share extension. I hope this helps others.

**Comment by smcenlly** [comment]
The error that you received is because you added Quokka development-time debug setting. While it looks like it helped you isolate the issue to Live Share, that setting is internal and will cause production releases to fail to start up.

It also looks like your VS Live Share extension was very old (from July). Might be worth updating that also?

**Comment by corysimmons** [comment]
I have updated extensions.

I can confirm this is still broken when LiveShare is installed/enabled.

**Comment by smcenlly** [comment]
Everything is working for us using the latest version of Live Share (1.0.488), latest version of Quokka (1.0.233) and latest version of VS Code (1.36.0).

Could you please provide us with a few more details?

1) Could you please confirm that the error the same as the original post `command 'quokka.createJavaScriptFile' not found`?
2) Immediately after launching a new instance of VS Code, please run the command `Developer: Toggle Developer Tools`  and provide us with the Console.log.
3) In your terminal, please run `code --list-extensions` and share the output.

**Comment by atif089** [comment]
Running into a similar issue, here's my stack trace.

```
abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:840
console.ts:137 [Extension Host] (node:9316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:140
console.ts:137 [Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

console.ts:137 [Extension Host] PHP process connected
abstractExtensionService.ts:717 Activating extension 'ms-vsliveshare.vsliveshare' failed: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'.
_logMessageInConsole @ abstractExtensionService.ts:663
workbench.html:1 A cookie associated with a cross-site resource at https://visualstudio.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
t.log @ console.ts:140
console.ts:137 [Extension Host] stack trace: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'	at ChildProcess.<anonymous> (c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\out\prod\extension-prod.js:151898:32)	at ChildProcess.emit (events.js:228:7)	at maybeClose (internal/child_process.js:1021:16)	at Socket.<anonymous> (internal/child_process.js:430:11)	at Socket.emit (events.js:223:5)	at Pipe.<anonymous> (net.js:664:12)
t.log @ console.ts:140
mainThreadExtensionService.ts:65 [[object Object]]Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
	at ChildProcess.<anonymous> (c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\out\prod\extension-prod.js:151898:32)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
$onExtensionRuntimeError @ host.ts:10
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
t.log @ console.ts:140
console.ts:137 [Extension Host] stack trace: Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'	at ChildProcess.<anonymous> (c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\out\prod\extension-prod.js:151898:32)	at ChildProcess.emit (events.js:228:7)	at maybeClose (internal/child_process.js:1021:16)	at Socket.<anonymous> (internal/child_process.js:430:11)	at Socket.emit (events.js:223:5)	at Pipe.<anonymous> (net.js:664:12)
t.log @ console.ts:140
mainThreadExtensionService.ts:65 [[object Object]]Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
$onExtensionRuntimeError @ host.ts:10
mainThreadExtensionService.ts:66 Error: Agent terminated with exit code: 0 and signal null: Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.osx-x64.Microsoft.NETCore.App', version: '3.1.1-servicing.19608.4'
    path: 'runtimes/osx-x64/native/System.Globalization.Native.dylib'
	at ChildProcess.<anonymous> (c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\out\prod\extension-prod.js:151898:32)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
$onExtensionRuntimeError @ host.ts:10
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, unlink 'c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\cascade.json'
t.log @ console.ts:140
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, unlink 'c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\cascade.json'
t.log @ console.ts:140
log.ts:197   ERR ENOENT: no such file or directory, unlink 'c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\cascade.json': Error: ENOENT: no such file or directory, unlink 'c:\Users\Atif\.vscode\extensions\ms-vsliveshare.vsliveshare-1.0.3206\cascade.json'
console.ts:137 [Extension Host]% Array(6)
console.ts:137 [Extension Host] Loaded config default.
t.log @ console.ts:140
console.ts:137 [Extension Host] 
Fixed all files in 0.013 seconds, 10.000 MB memory used
console.ts:137 [Extension Host] 
Files that were not fixed due to errors reported during linting before fixing:
   1) C:\Users\Atif\AppData\Local\Temp\functions.php
t.log @ console.ts:140
notificationsAlerts.ts:40 Command 'Quokka.js: New JavaScript File' resulted in an error (command 'quokka.createJavaScriptFile' not found)
onDidChangeNotification @ breadcrumbsModel.ts:39
notificationsAlerts.ts:40 Command 'Quokka.js: New JavaScript File' resulted in an error (command 'quokka.createJavaScriptFile' not found)
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
error @ breakpointWidget.ts:390
accept @ commandsQuickAccess.ts:126
async function (async)
accept @ commandsQuickAccess.ts:126
(anonymous) @ pickerQuickAccess.ts:186
fire @ event.ts:584
(anonymous) @ quickInput.ts:729
fire @ event.ts:584
(anonymous) @ quickInput.ts:1234
```


And a list of extensions
```
biamacedo.perl-html-template
blanu.vscode-styled-jsx
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
Equinusocio.vsc-community-material-theme
esbenp.prettier-vscode
felixfbecker.php-debug
felixfbecker.php-intellisense
hangxingliu.vscode-nginx-conf-hint
hashicorp.terraform
humao.rest-client
junstyle.php-cs-fixer
liximomo.sftp
mikestead.dotenv
mrmlnc.vscode-apache
ms-azuretools.vscode-docker
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.sublime-keybindings
ms-vsliveshare.vsliveshare
neilbrayfield.php-docblocker
nsfilho.tosnippet
octref.vetur
PKief.material-icon-theme
ritwickdey.LiveServer
shd101wyy.markdown-preview-enhanced
sleistner.vscode-fileutils
taniarascia.new-moon-vscode
WallabyJs.quokka-vscode
wordpresstoolbox.wordpress-toolbox
Shan.code-settings-sync
```

**Comment by passionkind** [comment]
I've got the same problem. But I'm running code insiders. When I uninstall live share, it works fine.

**Comment by wesbos** [comment]
same problem here

**Comment by smcenlly** [comment]
@wesbos - the problem appears to be related to VS Code Insiders and using the VS Code Live Share plugin. Something broke recently (we reported the issue [here](https://github.com/MicrosoftDocs/live-share/issues/4551)). 

Could you please try using the latest version of VS Code Insiders (you may need to check for an update) and let us know if you're still having the problem? If you are, can you please share your VS Code version information?

**Comment by wesbos** [comment]
Thanks, I have insiders installed but I'm not using it. Just stable VS Code. Will sit on my hands for a few weeks to see if it's fixed

**Comment by smcenlly** [comment]
As of this morning, we have tested the latest version of VS Code (stable) and VS Code Insiders, and everything appears to be working.

If you're still having the problem, can you please ensure that you have the latest VS Code version. If you are having a problem with the latest VS Code version, please provide your VS Code version/operating system details below.

**Comment by smcenlly** [comment]
Our problem with Live Share was caused by a promise that failed to resolve/reject. We have updated our integration with Live Share to be tolerant of this.

Please try updating to the latest version of Quokka for VS Code, `v1.0.436`. We believe this will resolve the problem.

**Comment by rogercamps** [comment]
Hi there, I just got the same problem, any known solution for this? 

thanks.

**Comment by smcenlly** [comment]
@rogercamps - what version of Quokka.js are you using?
