### ISSUE TITLE
WebStorm: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of com/intellij/ide/util/treeView/AbstractTreeUi.getNodeForElement must not be null

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/quokka#320]
### Issue description or question

At random points whether I use or do not use Quokka actively, I see red warning light in the status bar and it tells me there was an issue in the Quokka plugin. Otherwise, this issue is not really visible in the interface (afaict), but it's a small annoyance because it triggers the distracting red light in the status bar.

Full traceback:

```
com.quokka.javascript.M

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'element' of com/intellij/ide/util/treeView/AbstractTreeUi.getNodeForElement must not be null
	at com.intellij.ide.util.treeView.AbstractTreeUi.$$$reportNull$$$0(AbstractTreeUi.java)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getNodeForElement(AbstractTreeUi.java)
	at com.quokka.javascript.a.a.g.run(Unknown Source)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:267)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:23)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.maybeRunAfterUpdate(AbstractTreeUpdater.java:273)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:251)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$1.run(AbstractTreeUpdater.java:209)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:3069)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:356)
	at com.intellij.util.Alarm$Request.run(Alarm.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I have omitted samples as Quokka was not open when I was using it. I have no custom Quokka config.

### Code editor version

WebStorm 2018.3.3
Build #WS-183.5153.33, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

Windows 10 10.0

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.137.
