### ISSUE TITLE
IDE error when closing a scratch file

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/quokka#321]
### Issue description or question

As I was closing a scratch file I got this error from WebStorm:

```
java.lang.Throwable: Assertion failed: Already disposed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:174)
	at com.intellij.util.Alarm.checkDisposed(Alarm.java:67)
	at com.intellij.util.Alarm._addRequest(Alarm.java:194)
	at com.intellij.util.Alarm.addRequest(Alarm.java:169)
	at com.quokka.javascript.session.O.a(Unknown Source)
	at com.quokka.javascript.session.O.consume(Unknown Source)
	at com.quokka.javascript.session.QuokkaSession$c.a(Unknown Source)
	at com.quokka.javascript.session.QuokkaSession$c.a(Unknown Source)
	at com.quokka.javascript.session.S.run(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:280)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:277)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$0(QueueProcessor.java:79)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:79)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$3(QueueProcessor.java:212)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Code editor version

WebStorm 2018.3.3
Build #WS-183.5153.33, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Thanks for reporting this issue. This has been fixed in the latest version of Quokka for IntelliJ editors, v1.0.138.
