### ISSUE TITLE
Quokka stopped working on vscode 

### ISSUE THREAD

**Issue by Darksoulsong** [wallabyjs/quokka#352]
### Issue description or question
Quokka is not detecting when the code gets updated.

### Sample code

```javascript
   
   const arr = [1,5,6];

    console.log(arr)
```
### Quokka.js Console Output

```
Quokka 'Untitled-1.js (node:v11.0.0)
foo at quokka.js:3:0
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.33.0

### OS name and version
Linux Mint 19.1

![quokka error](https://user-images.githubusercontent.com/2078582/55899081-52937f00-5b9a-11e9-880a-5adc95bb7596.gif)

**Comment by smcenlly** [comment]
Unfortunately we can't reproduce the problem (we've tried in Linux using the same version of node with VS Code v1.33.0).

Can you please do the following for us:

1) Add a new setting, `debug` with a value `true` in your global quokka `config.json` file (https://quokkajs.com/docs/configuration.html#global-config-file):

```json
{
  "pro": true,
  "debug": true
}
```

2) In your VS Code, launch the developer tools with the command `Developer: Toggle Developer Tools`.
3) Duplicate the problem, and stop your key strokes as soon as the indicator icon seems to hang (in your screenshot, this appears to be when `const arr = console.log('foo')`.
4) Provide us with the full Developer Tools console.log output at this point in time.
5) Go back to the Quokka file that isn't working, and run the command, `Quokka.js: Show Instrumented Code` and also provide us with that code.

**Comment by Darksoulsong** [comment]
@smcenlly  Thank you for the reply. 
I think I sorted some things out: when I managed to disable the typescript validation through vscode settings, Quokka started to work as expected. And I can see an error regarding tsserver, like below:

```
[Extension Host]  [Info]  #Untitled-1.js Thu, 11 Apr 2019 12:31:57 GMT wallaby:project Test run result processed and sent to IDE
log.ts:173   ERR TypeScript Server Error (3.4.1)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:123449:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (tsserver.js:129779:42)
    at IOSession.Session.getOutliningSpans (tsserver.js:129793:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:128868:61)
    at tsserver.js:130451:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130442:28)
    at IOSession.Session.executeCommand (tsserver.js:130451:33)
    at IOSession.Session.onMessage (tsserver.js:130473:35)
    at Interface.<anonymous> (tsserver.js:131770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20): Error: TypeScript Server Error (3.4.1)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:123449:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (tsserver.js:129779:42)
    at IOSession.Session.getOutliningSpans (tsserver.js:129793:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:128868:61)
    at tsserver.js:130451:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130442:28)
    at IOSession.Session.executeCommand (tsserver.js:130451:33)
    at IOSession.Session.onMessage (tsserver.js:130473:35)
    at Interface.<anonymous> (tsserver.js:131770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:174464)
	at v.dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:179770)
	at v.dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:178522)
	at constructor._reader.onData.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:177878)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at t.Reader.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:183738)
	at Socket.t.Reader.constructor.e.on.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
log.ts:173   ERR TypeScript Server Error (3.4.1)
Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
    at InferredProject.Project.updateGraph (tsserver.js:125074:38)
    at updateProjectIfDirty (tsserver.js:125923:45)
    at updateGraph (tsserver.js:126304:34)
    at Array.forEach (<anonymous>)
    at ProjectService.ensureProjectStructuresUptoDate (tsserver.js:126308:39)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:126285:22)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:126282:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:129788:87)
    at IOSession.Session.getFileAndProject (tsserver.js:129771:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:130225:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:129052:61)
    at tsserver.js:130451:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130442:28)
    at IOSession.Session.executeCommand (tsserver.js:130451:33)
    at IOSession.Session.onMessage (tsserver.js:130473:35)
    at Interface.<anonymous> (tsserver.js:131770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20): Error: TypeScript Server Error (3.4.1)
Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
    at InferredProject.Project.updateGraph (tsserver.js:125074:38)
    at updateProjectIfDirty (tsserver.js:125923:45)
    at updateGraph (tsserver.js:126304:34)
    at Array.forEach (<anonymous>)
    at ProjectService.ensureProjectStructuresUptoDate (tsserver.js:126308:39)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:126285:22)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:126282:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:129788:87)
    at IOSession.Session.getFileAndProject (tsserver.js:129771:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:130225:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:129052:61)
    at tsserver.js:130451:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130442:28)
    at IOSession.Session.executeCommand (tsserver.js:130451:33)
    at IOSession.Session.onMessage (tsserver.js:130473:35)
    at Interface.<anonymous> (tsserver.js:131770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:174464)
	at v.dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:179770)
	at v.dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:178522)
	at constructor._reader.onData.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:177878)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at t.Reader.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:183738)
	at Socket.t.Reader.constructor.e.on.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:183386)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by smcenlly** [comment]
Thanks for letting us know. It looks like there may be something wrong with the TypeScript compiler, or VS Code that needs to be reported to one of those teams. We'd be happy to help you report that if we can duplicate the problem.

Can you get the same hang when `Initializing JS/TS Language Features` that you have in your screenshot when you're not using Quokka? If so, it might be worth reporting [here](https://github.com/Microsoft/vscode/issues).

If you'd like us to help you report, can you please provide your project tsconfig.json (if you had one) and a list of all of VS Code extensions?

**Comment by sidferreira** [comment]
I'm having the same issue. The problem was in a plugin named `Highlight line`
