### ISSUE TITLE
Error: EIO: i/o error, read 

### ISSUE THREAD

**Issue by donnisnoni95** [wallabyjs/quokka#355]
### Sample code

```javascript
var a = 2
```

### Quokka.js Console Output

```
Error: EIO: i/o error, read 
    at Object.readSync (fs.js:493:3) 
    at tryReadSync (fs.js:332:20) 
    at Object.readFileSync (fs.js:361:19) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:20) 
    at Module.load (internal/modules/cjs/loader.js:600:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
    at Module.require (internal/modules/cjs/loader.js:637:17) 
    at require (internal/modules/cjs/helpers.js:22:18) 
    at Module._compile (internal/modules/cjs/loader.js:701:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
    at Module.load (internal/modules/cjs/loader.js:600:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
    at Module.require (internal/modules/cjs/loader.js:637:17) 
    at require (internal/modules/cjs/helpers.js:22:18) 
    at Module._compile (internal/modules/cjs/loader.js:701:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
    at Module.load (internal/modules/cjs/loader.js:600:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
    at Module.require (internal/modules/cjs/loader.js:637:17) 
    at require (internal/modules/cjs/helpers.js:22:18) 
    at Module._compile (internal/modules/cjs/loader.js:701:30) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
    at Module.load (internal/modules/cjs/loader.js:600:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12) 
    at startup (internal/bootstrap/node.js:283:19) 
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) 
```

### Code editor version

Visual Studio Code v1.33.1?

### OS name and version

Linux Mint 19.1 Cinnamon

**Comment by ArtemGovorov** [comment]
The error looks specific to your environment (we have never seen it before in Quokka), and is related to failed attempt to read/load your project/Quokka dependencies. Unfortunately we can't recommend much other than 
- trying to reboot your machine,
- trying to re-install the plugin,
- investigating [what could be causing the issue in your environment](https://www.google.com/search?{google:acceptedSuggestion}oq=linux+EIO%3A+i%2Fo+error%2C+read&{google:instantFieldTrialGroupParameter}sourceid=chrome&ie=UTF-8&q=linux+EIO%3A+i%2Fo+error%2C+read).
