### ISSUE TITLE
[webstorm] java.lang.IllegalArgumentException: Argument for @NotNull parameter 'component' of com/intellij/util/ui/UIUtil.isFocusAncestor must not be null

### ISSUE THREAD

**Issue by personafour** [wallabyjs/quokka#373]
### Issue description or question
Seems that Quokka crashes as soon as Webstorm starts. It isn't breaks or crashes anything but shows error flashing light at the bottom bar and doesn't show Quokka's icon on Toolbar.

Full traceback:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'component' of com/intellij/util/ui/UIUtil.isFocusAncestor must not be null
	at com.intellij.util.ui.UIUtil.$$$reportNull$$$0(UIUtil.java)
	at com.intellij.util.ui.UIUtil.isFocusAncestor(UIUtil.java)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeContent(ContentManagerImpl.java:164)
	at com.quokka.javascript.QuokkaView.a(Unknown Source)
	at com.quokka.javascript.session.p.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```   

### Code editor version
WebStorm 2019.1.2
Build #WS-191.7141.49, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version
macOS 10.14.4

**Comment by smcenlly** [comment]
We couldn't duplicate this problem, but we've updated the IntelliJ extension to perform an additional check before some of our application logic that should fix this for you. Please download the latest version of the Quokka IntelliJ v1.0.164. So that you can start WebStorm, you can remove Quokka by going to your plugins directory (`~/Library/Application Support/<PRODUCT><VERSION>`) and deleting the `quokka-intellij` folder.

**Comment by personafour** [comment]
Thanks, `Quokka v1.0.165` works fine! 👍
