### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by yourfavorite** [wallabyjs/quokka#387]
I get the following error when attempting to run Quokka in VS Code on any file.

### Quokka.js Console Output

```
​​​​Quokka 'get-pixels.js' (node: v8.2.1)​​​​
/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/node_modules/micromatch/index.js:44 
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true); 
                                                   ^^^ 
 
SyntaxError: Unexpected token ... 
    at Object.Module._extensions..js (module.js:580:10) 
    at Object.Module._extensions..js (module.js:580:10) 
    at r (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:114) 
    at /Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:305 
    at Object.require.i.32../chromeRunner.js (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:21:30350) 
    at r (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:254) 
    at /Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:305 
    at Object.require.i.18../instrumentor (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:16:30511) 
    at r (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:254) 
    at /Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:305 
    at Object.require.i.34../lib/app (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:22:16231) 
    at r (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:254) 
    at e (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:421) 
    at Object.<anonymous> (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:14:438) 
    at Object.<anonymous> (/Users/username/.vscode/extensions/wallabyjs.quokka-vscode-1.0.228/dist/wallaby/server.js:1) 
    at Generator.next (<anonymous>) 
```

### Code editor version

Mac VSC @ 1.35.1

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue was caused by a new core dependency node module that is not compatible with older node versions (updating your node to v8.15.x would have helped). The issue is fixed and the fix is published in v1.0.230.
