### ISSUE TITLE
NPE in IntelliJ Idea when moving editor from one vertically split group to another

### ISSUE THREAD

**Issue by asampal** [wallabyjs/quokka#391]
I had my Idea window vertically split (into two), with a JavaScript scratch file (with Quokka running against it) opened in the left side. I grabbed the editor tab and attempted to move it to the the right side group of editors. The following NPE was thrown:

```
java.lang.NullPointerException
	at com.quokka.javascript.QuokkaView.a(Unknown Source)
	at com.quokka.javascript.session.q.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:782)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:731)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

System Details:
IU-192.5438.14, JRE 11.0.3 12-b304.2x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 3840x2160

**Comment by smcenlly** [comment]
Thanks for reporting the error and for the detailed instructions for reproducing. Unfortunately we couldn't reproduce on Windows or Mac so are unsure as to the cause. We've spotted a few places this error might be coming from and have released a new version of Quokka for IntelliJ that we think will fix your problem. 

Please download the latest version (v1.0.185). Let us know if this doesn't fix it for you and we'll reopen the issue.
