### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by asampal** [wallabyjs/quokka#395]
I'm getting the following exception when starting up Idea with three different projects in three separate windows:

```
java.lang.NullPointerException
	at com.quokka.javascript.session.Q.run(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

System details:
IU-192.5728.98, JRE 11.0.3 12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 3840x2160

**Comment by smcenlly** [comment]
Can you please confirm that you are using the latest version of Quokka for IntelliJ, v1.0.187?

In the meantime, we'll investigate further.

**Comment by asampal** [comment]
Yes, I'm on Quokka v. 1.0.187

**Comment by smcenlly** [comment]
Unfortunately we still can't duplicate the problem, but we have found a possible race condition that can lead to a null pointer exception in the same function that is reported in your stack trace. Please update to the latest version of Quokka for IntelliJ, v1.0.188 that addresses the issue we found.

If you're still having the problem, we will reopen this issue and could you also please provide us with your full IntelliJ idea log? You can find this from within IntelliJ using `Help`->`Show Log`.
