### ISSUE TITLE
Unable to save license key error

### ISSUE THREAD

**Issue by joelwat** [wallabyjs/quokka#414]
### Issue description or question
I'm trying to try to pro version of quokka. From the command palette I choose `Quokka.js: Manage License Key`. I paste in the license key from the email I got, press Enter and get a popup message that says `Unable to save license key: The "path" argument must be one of type string, Buffer, or URL. Received type undefined`

### Sample code

This doesn't involve any code

### Quokka.js Console Output
I'm not sure if this is related but this is in the Log(Window) output.
```
[2019-09-18 09:30:15.585] [renderer1] [error] 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true'): TypeError: 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')
    at /home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:22291
    at Array.forEach (<anonymous>)
    at h._getThemableDecorationRenderOptions (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:22249)
    at h._createCoverageDecorationType (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:22582)
    at h._initializeCoverageDecorationTypes (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:13252)
    at new h (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:11721)
    at r.<anonymous> (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:2439)
    at /home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:1745
    at Object.next (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:1850)
    at i (/home/joel/.vscode-insiders/extensions/wallabyjs.quokka-vscode-1.0.247/dist/index.js:6:596)
```

### Code editor version

Visual Studio Code v1.39.0-insider

### OS name and version

Linux - OpenSUSE Tumbleweed

**Comment by smcenlly** [comment]
Thanks for reporting the problem. The console log that you provided was important to allowing us identify the root cause of the error. It seems there's been a slight change in VS Code API that caused the problem. We've fixed this in in Quokka.js for VS Code v1.0.248. Please update your extension to the latest version to get the fix.

**Comment by joelwat** [comment]
Thanks for the quick fix!
