### ISSUE TITLE
Add Live Compare support for Number, Boolean, and Function data types

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#415]
Add Live Compare support for Number, Boolean, and Function data types

**Comment by Alexsey** [comment]
Function data type comparison works fine:
```
(function (x) { return x }), (a, b) => a + b

x => x, 33
```
Outputs
```
Quokka #1 (node: v12.10.0)

	at 	function (x) {
	    return x;
	} vs (a, b) => a + b _.js:1:1

	at 	x => x vs 33 _.js:3:0
```
![fnCompare](https://user-images.githubusercontent.com/6392013/65310351-cfd60d80-db96-11e9-949f-bf9ca825c299.png)

Problematic types are Numbers, Boolean and Null. Although, all they are comparable to functions
```
x => x, 33
x => x, true
x => x, null
```
Console
```
Quokka #1 (node: v12.10.0)

	at 	x => x vs 33 _.js:1:1

	at 	x => x vs true _.js:2:0

	at 	x => x vs null _.js:3:0
```
![fnCompare2](https://user-images.githubusercontent.com/6392013/65310522-2e9b8700-db97-11e9-97fb-ff83e44fc6df.png)

So maybe there is a correct diff for all types and it's just need to be output?

**Comment by Alexsey** [comment]
There are two ways to show diff:
1.
```
'4', '5'
```
would show
```
45
	at 	_.js:3:0
```
2.
```
() => {}, 5
```
would show
```
	at 	() => {
	} vs 5 _.js:1:1
```
If expected behavior for
```
4, 5
```
is like 2 - I think it can be already enabled, because if Function vs. Number works fine - Number vs. Number should also work fine
If the expected behavior is like 1 (that is definitely better), maybe until it's implementation is not trivial, option 2 can be enabled as a fast temporary solution?
