### ISSUE TITLE
SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by d3skdev** [wallabyjs/quokka#435]
### Issue description or question

I got an error when i choose 'Quokka: New TypeScript File' from  command palette
Uninstalling the extension didn't fixed the error.

This issue occurs with  v1.0.261 & v1.0.260.
Previous versions are working without any issues.

### Quokka.js Console Output

```
​​​​Quokka​​​​
/Users/top/.vscode/extensions/wallabyjs.quokka-vscode-1.0.261/dist/wallaby/node_modules/chokidar/index.js:151 
  async remove(item) { 
        ^^^^^^ 
 
SyntaxError: Unexpected identifier 
    at createScript (vm.js:56:10) 
    at Object.runInThisContext (vm.js:97:10) 
    at Module._compile (module.js:549:28) 
    at Object.Module._extensions..js (module.js:586:10) 
    at Module.load (module.js:494:32) 
    at tryModuleLoad (module.js:453:12) 
    at Function.Module._load (module.js:445:3) 
    at require (internal/module.js:20:19) 
    at Module._compile (module.js:577:32) 
    at Object.Module._extensions..js (module.js:586:10) 
    at Module.load (module.js:494:32) 
    at tryModuleLoad (module.js:453:12) 
    at Function.Module._load (module.js:445:3) 
    at Module.runMain (module.js:611:10) 
    at run (bootstrap_node.js:394:7) 
    at startup (bootstrap_node.js:160:9) 
    at bootstrap_node.js:507:3 
```

### Code editor version

Visual Studio Code v1.40.1

### OS name and version

OSX

**Comment by smcenlly** [comment]
This error indicates that you are running a version of node prior to v8.0.0. 

As of v1.0.260, Quokka no longer supports node versions prior to v8.x (v7.x end of life was June 2017, and v6.x end of life was April 2019).

Could you please confirm your version of node.js and [update to a current version](https://nodejs.org/en/)?

**Comment by d3skdev** [comment]
Im using Node v12.13.1

**Comment by smcenlly** [comment]
So that we can confirm that there's nothing special about Node.js for your system being overridden in your VS Code, could you please perform the following steps and provide us with the result:

1. Open VS Code
2. Run the command, `Developer: Toggle Developer Tools`
3. Navigate to the `Console` tab
4. In the console, run this script: 

```
console.log(require('child_process').execSync('node --version').toString())
```

5. Provide us with the result (it should be: `v12.13.1`)

**Comment by smcenlly** [comment]
@d3skdev - were you able to confirm the node version being reported from VS Code?

**Comment by smcenlly** [comment]
We're going to assume that you resolved the problem. If not, please let us know and we will re-open this issue.
