### ISSUE TITLE
Quokka not starting

### ISSUE THREAD

**Issue by MarkLopresto** [wallabyjs/quokka#438]
### Issue description or question
Quokka is no longer starting in VS Code

### Sample code

```javascript
// paste the code you are running here
const drinks = [
  { price: 2.20, name: 'Coffee'},
  { price: 1.80, name: 'Water'},
  { price: 3.99, name: 'Kombucha'},
];

const value = drinks.reduce((prev, next) => prev + next.price, 0)

console.log(value);
```

### Quokka.js Console Output

```
// paste your quokka console output here
/Users/marklopresto/.vscode/extensions/wallabyjs.quokka-vscode-1.0.262/dist/wallaby/node_modules/chokidar/index.js:904 
  const options = {type: EV_ALL, alwaysStat: true, lstat: true, ...opts}; 
                                                                ^^^ 
SyntaxError: Unexpected token ... 
    at Object.exports.runInThisContext (vm.js:78:16) 
    at Module._compile (module.js:545:28) 
    at Object.Module._extensions..js (module.js:582:10) 
    at Module.load (module.js:490:32) 
    at tryModuleLoad (module.js:449:12) 
    at Function.Module._load (module.js:441:3) 
    at require (internal/module.js:20:19) 
    at Module._compile (module.js:573:32) 
    at Object.Module._extensions..js (module.js:582:10) 
    at Module.load (module.js:490:32) 
    at tryModuleLoad (module.js:449:12) 
    at Function.Module._load (module.js:441:3) 
    at Module.runMain (module.js:607:10) 
    at run (bootstrap_node.js:420:7) 
    at startup (bootstrap_node.js:139:9) 
    at bootstrap_node.js:535:3 
```

### Code editor version

Visual Studio Code v1.40.2

### OS name and version

macOS Mojave 10.14.6

**Comment by smcenlly** [comment]
The error that you're receiving indicates that your version of node used by Quokka is earlier than node.js v8.0.0. Please [update your system node version](https://nodejs.org/) to node v8.x+.
