### ISSUE TITLE
How to test real time with a simple snippet?

### ISSUE THREAD

**Issue by daron4ever** [wallabyjs/quokka#455]
### Issue description or question
I just want to see the result of the itemTotal variable in live.

### Sample code

```javascript
var item1;
var item2;
var itemTotal = [item1, item2].join(",");
```

### Quokka.js Console Output

```
SyntaxError: Unexpected token { 
    at exports.runInThisContext (vm.js:53:16) 
    at Module._compile (module.js:373:25) 
    at Object.Module._extensions..js (module.js:416:10) 
    at Module.load (module.js:343:32) 
    at Function.Module._load (module.js:300:12) 
    at Module.require (module.js:353:17) 
    at require (internal/module.js:12:17) 
    at Module._compile (module.js:409:26) 
    at Object.Module._extensions..js (module.js:416:10) 
    at Module.load (module.js:343:32) 
    at Function.Module._load (module.js:300:12) 
    at Function.Module.runMain (module.js:441:10) 
    at startup (node.js:139:18) 
    at node.js:974:3 
```

**Comment by smcenlly** [comment]
The following snippet should work for you if you want to output `itemTotal`:

```javascript
var item1;
var item2;
var itemTotal = [item1, item2].join(",");

itemTotal
```

You may also output the itemTotal by simply selecting the `itemTotal` variable name beside its declaration, i.e. "var `itemTotal`".

From what you've provided, it looks like your sample and your Quokka console output are both truncated. Are you able to provide the full sample code and full Quokka output? 

Another possible cause for your error is that you are running an older version of [node.js](https://nodejs.org/en/). Please also try updating to the latest LTS or current version.

**Comment by daron4ever** [comment]
The problem was my old node.js version.
It works like a charm after updating.
Thanks.
