### ISSUE TITLE
Array literal is evaluated to undefined

### ISSUE THREAD

**Issue by jsamr** [wallabyjs/quokka#462]
### Issue description or question

Array literal is evaluated to undefined

### Sample code

```javascript
const reducer = (acc, val) => {
    return acc+val
}

reducer(10, 5) /*?*/

[0,1,2,3,4,5].reduce(reducer, 0) /*?*/
```

### Quokka.js Console Output

```bash
​​​​Quokka 'test.js' (node: v12.14.1)​​​​
 
Cannot read property 'reduce' of undefined 
  at ​test.js:5:0​

15 ​​​​​at ​​​reducer(10, 5)​​​ ​test.js:5:0​
```

### Observations

- the output claims the error appears at line 5, while the reduce function is evaluated line 7
- unable to reproduce after removing line 5

### Code editor version

Visual Studio Code v1.41.1
Quokka v1.0.277

### OS name and version

``` bash
 ██████████████████  ████████     jsamr@jsamr-nuc
 ██████████████████  ████████     OS: Manjaro 18.1.5 Juhraya
 ██████████████████  ████████     Kernel: x86_64 Linux 5.3.18-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 3h 34m
 ████████           ████████     Packages: 1799
 ████████  ████████  ████████     Shell: zsh 5.7.1
 ████████  ████████  ████████     Resolution: 3840x1080
 ████████  ████████  ████████     DE: KDE 5.66.0 / Plasma 5.17.5
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus
 ████████  ████████  ████████     Font: Noto Sans Regular
 ████████  ████████  ████████     Disk: 814G / 932G (92%)
 ████████  ████████  ████████     CPU: Intel Core i7-8809G @ 8x 4.2GHz [55.0°C]
                                  GPU: AMD VEGAM (DRM 3.33.0, 5.3.18-1-MANJARO, LLVM 9.0.1)
                                  RAM: 10346MiB / 32037MiB

```

**Comment by smcenlly** [comment]
Thanks for your sample. The results that you are seeing are expected and you get the same results when you run your code outside of Quokka using `node`:

```
$ node test.js
test.js:7
[0,1,2,3,4,5].reduce(reducer, 0) /*?*/
             ^

TypeError: Cannot read property 'reduce' of undefined
    at Object.<anonymous> (test.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

What's effectively happening is that what you want to be an array literal in an ExpressionStatement is actually being treated as a SequenceExpression. The JavaScript runtime sees your code as:

```
reducer(10, 5)[0,1,2,3,4,5].reduce(reducer, 0)
```

The SequenceExpression after your CallExpression returns undefined, which is why you're getting the error.

A quick fix for you is to put a semicolon after `reducer(10, 5)` to tell the JavaScript runtime that the statement has terminated.
