### ISSUE TITLE
React missing ​​requestAnimationFrame jsdom-quokka

### ISSUE THREAD

**Issue by marcoSven** [wallabyjs/quokka#492]
### Issue description or question
How to add a shim to jsdom-quokka, to fix missing ​​requestAnimationFrame in jsdom for example?
### Sample code

```javascript
global.requestAnimationFrame = fun => fun();
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

const div = document.createElement('div');
ReactDOM.render(<App />, div);
div.getElementsByClassName('App')[0].innerHTML //?
```

### Sample repository link

https://gitlab.com/marcoSven/react-requestanimationframe/-/blob/master/src/App.js#L6

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
Quokka 'quokka-create-react-app/src/index.js' (node: v14.3.0, Babel: 7.9.0, plugins: jsdom-quokka-plugin)​​​​

- 
- 

​​requestAnimationFrame is not defined​​
  ​​​App ​​​at  
  ​​​renderWithHooks ​​​at  
  ​​​mountIndeterminateComponent ​​​at  
  ​​​beginWork ​​​at  
  ​​​HTMLUnknownElement.callCallback ​​​at  
  ​​​innerInvokeEventListeners ​​​at  
  ​​​invokeEventListeners ​​​at  
  ​​​HTMLUnknownElementImpl._dispatch ​​​at  
  ​​​HTMLUnknownElementImpl.dispatchEvent ​​​at  
  ​​​HTMLUnknownElement.dispatchEvent ​​​at  
  ​​​Object.invokeGuardedCallbackDev ​​​at  
  ​​​invokeGuardedCallback ​​​at  
  ​​​beginWork$1 ​​​at  
  ​​​performUnitOfWork ​​​at  
  ​​​workLoopSync ​​​at  
  ​​​performSyncWorkOnRoot ​​​at  
  ​​​scheduleUpdateOnFiber ​​​at  
  ​​​updateContainer ​​​at  
  at  
  ​​​unbatchedUpdates ​​​at  
  ​​​legacyRenderSubtreeIntoContainer ​​​at  
  ​​​Object.render ​​​at  
  ​​​Object.<anonymous> ​​​at  
  ​​​Module._compile ​​​at  

- 
- 

​​Error: Uncaught [ReferenceError: requestAnimationFrame is not defined]​​
​​    at reportException (~/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)​​
​​    at innerInvokeEventListeners (~/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:331:9)​​
​​    at invokeEventListeners (~/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)​​
​​    at HTMLUnknownElementImpl._dispatch (~/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)​​
​​    at HTMLUnknownElementImpl.dispatchEvent (~/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)​​
​​    at HTMLUnknownElement.dispatchEvent (~/.quokka/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)​​
​​    at Object.invokeGuardedCallbackDev (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:237:16)​​
​​    at invokeGuardedCallback (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:292:31)​​
​​    at beginWork$1 (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:23203:7)​​
​​    at performUnitOfWork (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:22157:12)​​
​​    at workLoopSync (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:22130:22)​​
​​    at performSyncWorkOnRoot (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:21756:9)​​
​​    at scheduleUpdateOnFiber (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:21188:7)​​
​​    at updateContainer (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:24373:3)​​
​​    at .../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:24758:7​​
​​    at unbatchedUpdates (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:21903:12)​​
​​    at legacyRenderSubtreeIntoContainer (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:24757:5)​​
​​    at Object.render (.../quokka-create-react-app/node_modules/react-dom/cjs/react-dom.development.js:24840:10)​​
​​    at Object.<anonymous> (.../quokka-create-react-app/src/index.js:11:37)​​
​​    at Module._compile (internal/modules/cjs/loader.js:1200:30)​​
​​    at Object.quokkaStackTraceMarker (...Application Support/Sublime Text/Packages/Quokka/wallaby/runners/node/quokka@1.0.0/initializer.js:14:5501)​​
​​    at a.quokkaStackTraceMarker [as _onStart] (...Application Support/Sublime Text/Packages/Quokka/wallaby/runners/node/quokka@1.0.0/initializer.js:14:5542)​​
​​    at a.start (...Application Support/Sublime Text/Packages/Quokka/wallaby/server.js:24:28218)​​
​​    at x.in:run (...Application Support/Sublime Text/Packages/Quokka/wallaby/server.js:19:22609)​​
​​    at WebSocket.<anonymous> (...Application Support/Sublime Text/Packages/Quokka/wallaby/server.js:19:20173)​​
​​    at WebSocket.emit (events.js:315:20)​​
​​    at Receiver.ontext (...Application Support/Sublime Text/Packages/Quokka/wallaby/node_modules/ws/lib/WebSocket.js:841:10)​​
​​    at ...Application Support/Sublime Text/Packages/Quokka/wallaby/node_modules/ws/lib/Receiver.js:536:18​​
​​    at ...Application Support/Sublime Text/Packages/Quokka/wallaby/node_modules/ws/lib/Receiver.js:368:7​​
​​    at ...Application Support/Sublime Text/Packages/Quokka/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5​​
​​    at afterWrite (_stream_writable.js:454:5)​​
​​    at onwrite (_stream_writable.js:434:7)​​
​​    at InflateRaw.afterTransform (_stream_transform.js:98:3)​​
​​    at Zlib.processCallback (zlib.js:580:8) [ReferenceError: requestAnimationFrame is not defined]​​

​​The above error occurred in the <App> component:​​
​​    in App (at src/index.js:7)​​
​​​​
​​Consider adding an error boundary to your tree to customize error handling behavior.​​
​​Visit https://fb.me/react-error-boundaries to learn more about error boundaries.​​
```

### Code editor version

ST4

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The `requestAnimationFrame` had been added in the newer versions of `jsdom` (behind the `pretendToBeVisual` flag), so it should be possible to use by:

- updating your `jsdom-quokka-plugin` plugin to latest (we have bumped `jsdom` dependency) in your Quokka config folder modules:
```
cd ~/.quokka && npm i jsdom-quokka-plugin@latest
```
- adding the [`pretendToBeVisual` JSDOM setting](https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser), wherever you have your Quokka config with `"plugins": ["jsdom-quokka-plugin"]`, you may add `jsdom-quokka-plugin` config as described in the [plugin docs](https://github.com/wallabyjs/jsdom-quokka-plugin#configuration):

```diff
{
    "plugins": ["jsdom-quokka-plugin"],
+   "jsdom": {
+     "config": {"pretendToBeVisual": true}
+   }
}
```
<img width="1413" alt="Screen Shot 2020-06-04 at 11 35 50 am" src="https://user-images.githubusercontent.com/979966/83705199-99262180-a657-11ea-9fb5-92bc604d5810.png">

**Comment by marcoSven** [comment]
Thank you @ArtemGovorov
