### ISSUE TITLE
Quokka not reevaluating Code / Updating

### ISSUE THREAD

**Issue by KeKs0r** [wallabyjs/quokka#50]
### Issue description or question
I think Quokka is not reevaluating my code. It is getting stuck at a point where I was still changing the code / typing and even when I finish the code its not running again or just stuck.

Is there a way to see what Quokka is internally doing?

### Quokka.js file

```javascript
const fs = require('fs');
const Path = require('path');
const Async = require('async');
const _ = require('lodash');


function collect(path, cb) {
    fs.readdir(path, (err, files) => {
        if (err) {
            return cb(err);
        }
        console.log(`Found ${files.length} folders`);
        const withoutSystem = files 
            .filter(filterSystem); /*? $.length */
        const file = Path.join(path, withoutSystem[0]);
        cb(null, file);
    })
}

function filterSystem(d) {
    const folderStart = d[0];
    return folderStart !== '.';
}


const basePath = Path.join(__dirname, '/..'); /*?*/
collect(basePath, (err, res) => {
    if (err) {
        console.error(err);
    }
    res;
    process.exit();
})

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above (for example because it requires/imports some files from your project), please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output
In Editor Error (Error does not align with code, since the code is actually fixed but quokka is still suck on a previous error)
```
cfiles not defined (in line 12, where I had a typo before fixing it)
```
![image](https://cloud.githubusercontent.com/assets/2970814/25702307/ae437fd6-30d0-11e7-8927-b42fadbd95c2.png)

Console Output:
```
​​​​Quokka #1 (node: v6.6.0)​​​​
​​Failed to parse quokka.js, SyntaxError: Unexpected token (12:51)​​
​​    at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​    at process._tickCallback (internal/process/next_tick.js:98:9)​​
​​    at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​    at process._tickCallback (internal/process/next_tick.js:98:9)​​
```

### Code editor version

Visual Studio Code Version 1.11.2 (1.11.2)
Node

### OS name and version
OSX

**Comment by KeKs0r** [comment]
I think the problem was that I was calling process.exit
