### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Songkeys** [wallabyjs/quokka#522]
### Sample code

```javascript
import dayjs from "dayjs"

dayjs

```
### Quokka.js Console Output

```
​​​​​Quokka 'test.ts' (node: v14.3.0, babel: v7.10.3, plugins: jsdom-quokka-plugin)​​​​
 
Cannot use import statement outside a module 
  at ​​​wrapSafe​​​ ​internal/modules/cjs/loader.js:1116​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1164​

```

Code without `import` statement used works. e.g.

```
```javascript
import dayjs from "dayjs"
```
```


### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 



project `package.json`:

```json
{
  "name": "uCourse-client-ts",
  "version": "1.0.0",
  "private": true,
  "description": "uCourse-client",
  "templateInfo": {
    "name": "default",
    "typescript": true,
    "css": "sass"
  },
  "scripts": {
    // ....
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "^3.0.5",
    "@tarojs/react": "^3.0.5",
    "@tarojs/runtime": "^3.0.5",
    "@tarojs/taro": "^3.0.5",
    "@tarojsx/history": "^0.32.0",
    "@types/classnames": "^2.2.10",
    "classnames": "^2.2.6",
    "dayjs": "^1.8.28",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "react-query": "^2.2.1",
    "taro-axios": "^1.1.1",
    "terser-webpack-plugin": "^3.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "^3.0.5",
    "@tarojs/mini-runner": "^3.0.5",
    "@tarojs/webpack-runner": "^3.0.5",
    "@types/react": "^16.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^2.x",
    "@typescript-eslint/parser": "^2.x",
    "babel-preset-taro": "^3.0.5",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-taro": "^3.0.5",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "husky": ">=4",
    "lint-staged": ">=10",
    "prettier": "^2.0.5",
    "stylelint": "9.3.0",
    "typescript": "^3.9.5",
    "webpack-bundle-analyzer": "^3.8.0"
  }
}

```

project `babel.config.js`

```js
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: true
    }]
  ]
}
```

project `.quokka`

```json
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "babel": {
    "ts": true
  }
}

```

global quokka: untouched.

(I tried to install/uninstall "jsdom-quokka-plugin", but no difference was made.)

### Code editor version

VS Code
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

### OS name and version

OS: Darwin x64 19.5.0

**Comment by smcenlly** [comment]
Your babel configuration needs to be updated to transform the import statement to `commonjs` format. You may get this working by changing your `.quokka` configuration to:

```json
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "babel": {
    "ts": true,
    "plugins": ["@babel/plugin-transform-modules-commonjs"],
    "presets": [
      [
        "taro",
        {
          "framework": "react"
        }
      ]
    ]
  }
}
```

**Comment by Songkeys** [comment]
Thank you so much. This solves the import issue. But it cannot tell a ts file:

```
​​​​​Quokka 'time.ts' (node: v14.3.0, babel: v7.10.3, plugins: jsdom-quokka-plugin)​​​​
SyntaxError: ./src/utils/time.ts: Unexpected token, expected "," (8:21) 
 
   7 |  
>  8 | const fromNow = (date: ConfigType, noSuffix: boolean = false): string => 
     |                      ^ 

```

Any further configuration I should do?

**Comment by smcenlly** [comment]
Sorry - we had assumed that your babel configuration from the `taro` preset was already working with TypeScript. You'll need to update your babel configuration to also use the typescript preset:

```javascript
...
    "presets": [
      "@babel/preset-typescript",
      [
        "taro",
        {
          "framework": "react"
        }
      ]
    ]
...
```

**Comment by Songkeys** [comment]
@smcenlly 
Thank you. the `taro` preset does work with TypeScript. It with a parameter `"ts": true` to indicate this. So I added it to the .quokka file:

```json
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "babel": {
    "ts": true,
    "plugins": [
      "@babel/plugin-transform-modules-commonjs"
    ],
    "presets": [
      [
        "taro",
        {
          "framework": "react",
          "ts": true
        }
      ]
    ]
  }
}
```

But I still got the import error:
```
​​​​​Quokka 'index.tsx' (node: v14.3.0, babel: v7.10.3, plugins: jsdom-quokka-plugin)​​​​
 
Must use import to load ES Module: ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js 
require() of ES modules is not supported. 
require() of ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js from ./src/packages/course/pages/evaluation/index.tsx is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. 
Instead rename slicedToArray.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./node_modules/@babel/runtime/helpers/esm/package.json. 
 
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1216​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:1049​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:937​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:73​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1200​

```

**Comment by smcenlly** [comment]
Can you please provide us with the code sample you are using when you get the error? 

FYI: the issue is likely to be related to your babel configuration (not an issue with Quokka). You should be able to reproduce the issue outside of Quokka with

```
npx babel index.tsx --out-file output.js
```

and then

```
node output.js
```

**Comment by Songkeys** [comment]
@smcenlly 
Not able to run this command: 
```
npx babel index.tsx --out-file output.js
npx: installed 1 in 2.847s
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall -g babel
    npm install --save-dev babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
```

And I don't think this is my babel issue, because I can run it in my normal project. Think it's a quokka config problem.

I created a minimal repo to reproduce this issue. Could you please help me figure this out? Thank you.
https://github.com/Songkeys/taro-test

**Comment by smcenlly** [comment]
I received the same error when attempting to use babel from the CLI. After installing the CLI, I get the same error when running from babel:

**Install babel CLI**
```
npm install --save-dev @babel/core @babel/cli
```

**Run Babel from CLI**
```
npx babel .\src\pages\index\index.tsx --out-file output.js
```

**Run node on file compiled using babel CLI**
```
import _classCallCheck from "C:\\Temp\\taro-test\\node_modules\\@babel\\runtime/helpers/esm/classCallCheck";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1117:16)
    at Module._compile (internal/modules/cjs/loader.js:1165:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

The error above is the same as what's happening when Quokka is running.

We'll take a look at what your babel configuration is doing to see if we can determine why for you.

**Comment by smcenlly** [comment]
The problem was stemming from the `babel-preset-taro` package where it is expecting an environment variable `NODE_ENV` to be set to `jest` or `test` in order for your code to work in `node`. See [here](https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/index.js#L109).

You may fix this by updating your Quokka configuration to:

```javascript
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "env": {
    "params": {
      "env": "NODE_ENV=test"
    }
  }
  "babel": {
    "ts": true,
    "plugins": [
      "@babel/plugin-transform-modules-commonjs"
    ],
    "presets": [
      [
        "taro",
        {
          "framework": "react",
          "ts": true
        }
      ]
    ]
  }
}
```

**Comment by Songkeys** [comment]
Thank you for your investigation. This does solve the import problem. But here comes the export problem now...This is so painful...

```
Quokka 'index.tsx' (node: v14.3.0, babel: v7.10.3, plugins: jsdom-quokka-plugin)​​​​
 
Unexpected token 'export' 
  at ​​​wrapSafe​​​ ​internal/modules/cjs/loader.js:1116​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1164​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1220​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:1049​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:937​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:1089​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:73​
  at ​​​Object.<anonymous>​​​ ​./node_modules/@tarojs/api/dist/index.js:5​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1200​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1220​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:1049​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:937​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:1089​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:73​
  at ​​​Object.<anonymous>​​​ ​./node_modules/@tarojs/taro/index.js:1​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1200​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1220​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:1049​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:937​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:73​
  at ​​​Object.<anonymous>​​​ ​src/components/RichContent/index.tsx:2​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1200​

```

**Comment by smcenlly** [comment]
We're not getting that error. Does your `index.tsx` file still have the contents as below?

```typescript
import React, { Component } from 'react'
import { View, Text } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
      </View>
    )
  }
}
```

This is the output that we receive:

![image](https://user-images.githubusercontent.com/2074089/89143905-85cbff80-d58f-11ea-9193-aeee7add9f97.png)

**Comment by Songkeys** [comment]
It turns out it's another issue: when I try to import `Taro` and use it:

```
import Taro from "@tarojs/taro";
```

**Comment by smcenlly** [comment]
The reason that this isn't working for you is that one or more of tarojs dependencies that are being used when you import from `@tarojs/taro` are published as ES modules. You need to let babel know that it needs to transpile these node modules for you when Quokka is running in node. You can get this working with:

```diff
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "env": {
    "params": {
      "env": "NODE_ENV=test"
    }
  },
  "babel": {
    "ts": true,
+   "ignore" : "node_modules/(?!@tarojs)",
    "plugins": [
      "@babel/plugin-transform-modules-commonjs"
    ],
    "presets": [
      [
        "taro",
        {
          "framework": "react",
          "ts": true
        }
      ]
    ]
  }
}
```

Please note that the problems that you have experienced are related to differences between the taro vs. node.js runtime, and not specific to Quokka.
