### ISSUE TITLE
JSDOM problems

### ISSUE THREAD

**Issue by tomasovic** [wallabyjs/quokka#525]
### Issue description or question

When I start the Quokka plugin, it's screaming that the element is missing, in this case, DIV with slider class. I have tried to install jsdom separately as for older versions, but no luck. Also tried to make some new extra config files, as per the documentation, but also no luck. The code is working properly and this is only part of it.

### jsdom plugin repository

README file for jsdom-quokka-plugin says no need to install this package for the newer version of Quokka, but after few failures, I tried to install it, locally and globally, again, no luck.

https://github.com/wallabyjs/jsdom-quokka-plugin

### Sample code

```javascript
function Slider(slider) {
  if (!(slider instanceof Element)) {
    throw new Error('No slider passed in'); // No slider passed in
  }
.... some code...
}

const mySlider = new Slider(document.querySelector('.slider')); // No slider passed in
```

### Quokka.js Console Output

```
​​​​​Quokka 'index-prototype.js' (node: v14.5.0, plugins: jsdom-quokka-plugin)​​​​
 
No slider passed in 
  at ​​​new Slider​​​ ​playing_code/exercises/59 - Slider/src/index-prototype.js:8:4​
  at ​playing_code/exercises/59 - Slider/src/index-prototype.js:72:0​
```

### Quokka version/VSCode extension

Quokka 1.0.312, PRO version

### Code editor version

Visual Studio Code v1.47.3

### OS name and version

OSX Catalina 10.15.6

**Comment by tomasovic** [comment]
Fixed it.

It was my mistake, bad HTML file path in the .quokka config file.

Closed.
