### ISSUE TITLE
Uncaught [SyntaxError: Unexpected token <]

### ISSUE THREAD

**Issue by finnolav** [wallabyjs/quokka#529]
### Error message showing in output even when no code is written.
node versjon: v12.10.0
quokka version 1.0.314

### Sample code

```javascript
// syntax error from the start, without writing any code.
```

### Quokka.js Console Output

```
Error: Uncaught [SyntaxError: Unexpected token <] 
    at reportException (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24) 
    at processJavaScript (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7) 
    at HTMLScriptElementImpl._innerEval (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:168:5) 
    at /Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:107:12 
    at ResourceQueue.push (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16) 
    at HTMLScriptElementImpl._fetchInternalScript (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:106:21) 
    at HTMLScriptElementImpl._eval (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:162:12) 
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:125:10) 
    at OpenElementStack.pop (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:17:12) 
    at Object.endTagInText [as END_TAG_TOKEN] (/Users/abc/.quokka/node_modules/parse5/lib/parser/index.js:2153:20) 
    at Parser._processToken (/Users/abc/.quokka/node_modules/parse5/lib/parser/index.js:657:55) 
    at Parser._processInputToken (/Users/abc/.quokka/node_modules/parse5/lib/parser/index.js:684:18) 
    at Parser._runParsingLoop (/Users/abc/.quokka/node_modules/parse5/lib/parser/index.js:440:18) 
    at Parser.parse (/Users/abc/.quokka/node_modules/parse5/lib/parser/index.js:344:14) 
    at Object.parse (/Users/abc/.quokka/node_modules/parse5/lib/index.js:10:19) 
    at HTMLToDOM._parseWithParse5 (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:64:19) 
    at HTMLToDOM._doParse (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:48:42) 
    at HTMLToDOM.appendToDocument (/Users/abc/.quokka/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:44:17) 
    at new JSDOM (/Users/abc/.quokka/node_modules/jsdom/lib/api.js:45:29) 
    at beforeEach (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/jsdomQuokkaPlugin.js:14:1070) 
    at /Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:7067 
    at Array.forEach (<anonymous>) 
    at a.<anonymous> (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:7047) 
    at r (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:1137) 
    at Object.next (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:432) 
    at /Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:331 
    at new Promise (<anonymous>) 
    at __awaiter (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:125) 
    at a.quokkaStackTraceMarker [as _onStart] (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:4120) 
    at a.start (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/server.js:25:26622) 
    at F.in:run (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/server.js:20:16581) 
    at WebSocket.<anonymous> (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/server.js:20:14094) 
    at WebSocket.emit (events.js:209:13) 
    at WebSocket.EventEmitter.emit (domain.js:476:20) 
    at Receiver.ontext (/Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/node_modules/ws/lib/WebSocket.js:841:10) 
    at /Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/node_modules/ws/lib/Receiver.js:536:18 
    at /Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/node_modules/ws/lib/Receiver.js:368:7 
    at /Users/abc/.vscode/extensions/wallabyjs.quokka-vscode-1.0.314/dist/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5 
    at afterWrite (_stream_writable.js:498:3) 
    at onwrite (_stream_writable.js:485:7) 
    at InflateRaw.afterTransform (_stream_transform.js:96:3) 
    at Zlib.processCallback (zlib.js:571:8) [SyntaxError: Unexpected token <] 
```

### Code editor version

Visual Studio Code v1.48.0?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please delete the `plugins` section from the `~/.quokka/config.json` file, delete ``~/.quokka/node_modules` folder and restart Quokka, it should help.

**Comment by finnolav** [comment]
That solved it, thanks!
