### ISSUE TITLE
vsCode 1.52.1 stopped working with quokka js

### ISSUE THREAD

**Issue by vim-daniel** [wallabyjs/quokka#572]
### Issue description or question

after upgrading vscode to version `1.52.1` quokka js stopped working,
doesn't really matter what i write in the quokka file

### Quokka.js Console Output

```
~/.vscode/extensions/wallabyjs.quokka-vscode-1.0.335/dist/wallaby/server.js:24 
stack:[]};if(t.spec){var a=n[t.spec]=n[t.spec]||[];a.push(o)}else e.globalErrors||(e.globalErrors=[]),e.globalErrors.push(o)}}),this._processValueExplorerValues(r),debug("Processed console.log entries"),_.each(t.loadingSequence,function(t,n){_.each(t,function(t){var r=i._structure.filesById[t];r&&!i.settings().ignoreFileLoadingDependencyTracking&&(r.testFilesLoadedFrom=r.testFilesLoadedFrom||{},r.testFilesLoadedFrom[n]=runAlways);var s=i._structure.testFilesById[t];if(n!==t&&s){var o=i._structure.testFilesById[n];o&&e.globalErrors.push({message:"Test file '"+o.path+"' is importing or is causing import of another test file '"+s.path+"'.\nThis may cause tests in the '"+s.path+"' file to be executed more than once (when the test file runs and every time it gets imported).\nIf the '"+s.path+"' test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing t 
 
SyntaxError: Invalid regular expression flags 
    at createScript (vm.js:56:10) 
    at Object.runInThisContext (vm.js:97:10) 
    at Module._compile (module.js:549:28) 
    at Object.Module._extensions..js (module.js:586:10) 
    at Module.load (module.js:494:32) 
    at tryModuleLoad (module.js:453:12) 
    at Function.Module._load (module.js:445:3) 
    at Module.runMain (module.js:611:10) 
    at run (bootstrap_node.js:394:7) 
    at startup (bootstrap_node.js:160:9) 
```

### Code editor version

Visual Studio Code v1.52.1

### OS name and version

OSX mojave 10.14.6

**Comment by smcenlly** [comment]
Could you please try uninstalling and reinstalling the Quokka for VS Code extension?

Could you also please tell us what node version you are using if you run `node --version` from your VS Code terminal?

**Comment by smcenlly** [comment]
I'm going to assume that a reinstall fixed your problem and close this issue. If not, please let us know and we will re-open it.

**Comment by supdegrave** [comment]
FYI, I encountered this issue as well. Reinstalling fixed the problem.

```
$ node --version
v10.19.0
```
