### ISSUE TITLE
global config

### ISSUE THREAD

**Issue by czaplej** [wallabyjs/quokka#573]
### Issue description or question
I would like to use global node_modules folder instead of local project node_modules for quokka

![image](https://user-images.githubusercontent.com/29889157/103441029-45aa9f00-4c4b-11eb-9e0b-cc2df984564b.png)

**config.js**
```
{
  "pro": true,
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "ts": true,
    "presets": ["react-app"]
  }
}
```

**package.json**
```
{
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "typescript": "^4.1.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "jsdom-quokka-plugin": "^1.0.16",
    "react-scripts": "^4.0.1",
    "@babel/register": "^7.12.10"
  }
}
```

### Quokka.js Console Output

```
Failed to run compilers on quokka.tsx, Cannot find module 'babel-preset-react-app' from '.'
    at Function.resolveSync (./node_modules/resolve/lib/sync.js:90:15)
    at resolveStandardizedName (./node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (./node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (./node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (./node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at ./node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (./node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (./node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at ./node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (./node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (./node_modules/gensync/index.js:251:28)
    at sync (./node_modules/gensync/index.js:89:14)
    at presets (./node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (./node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at ./node_modules/@babel/core/lib/config/config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (./node_modules/@babel/core/lib/config/config-chain.js:68:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (./node_modules/@babel/core/lib/config/partial.js:95:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (./node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Function.transform (./node_modules/@babel/core/lib/transform.js:25:45)
    at transform.next (<anonymous>)
    at evaluateSync (./node_modules/gensync/index.js:251:28)
    at Function.sync (./node_modules/gensync/index.js:89:14)
    at Object.transform (./node_modules/@babel/core/lib/transform.js:36:54)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

### Code editor version
Webstorm 2020.3

### OS name and version
OSX BIG SUR 11.1

**Comment by smcenlly** [comment]
Your error indicates that you're missing the `babel-preset-react-app` package. There are likely a few other babel packages you're also missing. If you add all missing packages, you should no longer get the `Cannot find module` error and you should be able to run Quokka by having these packages in your global Quokka folder.

**Comment by czaplej** [comment]
I will check but im almost sure that react-scripts has those all packages inside.
