### ISSUE TITLE
Quokkajs Webstorm Plugin Error

### ISSUE THREAD

**Issue by bdinesh** [wallabyjs/quokka#585]
### Getting fatal error in Webstorm 
![image](https://user-images.githubusercontent.com/676802/108349667-47cfb980-7209-11eb-8672-b20c8b36be90.png)

### Quokka.js Console Output

```
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Clear file values; ClearFileValueIntentionAction; while looking for description.html [Plugin: quokka.js]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:64)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:126)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.processMetaData(IntentionManagerSettings.java:187)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.java:220)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$1(SearchableOptionsRegistrarImpl.java:131)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:131)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.getAcceptableDescriptions(SearchableOptionsRegistrarImpl.java:354)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:185)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:126)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:96)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:179)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:196)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Code editor version

Webstorm v2020.3.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's fixed and the fix is published in the latest plugin version 1.0.277.
