### ISSUE TITLE
window object not detected. it shows undefined.

### ISSUE THREAD

**Issue by dkadam77** [wallabyjs/quokka#588]
Very simple JS code 
### Sample code

```javascript
var course = 'Hello'
console.log(window.course)

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

​​​​​Quokka 'script.js' (node: v14.16.0, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​

undefined ​​​​​at ​​​window.course​​​ ​script.js:69:0​

undefined ​​​​​at ​​​window.course​​​ ​script.js:69:0​



### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
The result is expected, there's no such built-in as `window.course`, so it is undefined. Looks you are missing a HTML page or another script that is supposed to load `window.course`. Hopefully [this docs section](https://quokkajs.com/docs/configuration.html#jsdom) should help.
