### ISSUE TITLE
Support for Vanilla JS

### ISSUE THREAD

**Issue by Prodesed** [wallabyjs/quokka#597]
### Issue description or question
I updated the config file for quokka globally to include the support for react files and when I started to work with vanilla JS, quokka is giving an error. So, to work with vanilla JS projects in the future, do I have to always change the config file to work with vanilla JS?

This is my global config file for quokka:
```
{
  "plugins": ["jsdom-quokka-plugin"],
  "babel": { "presets": ["react-app"] }
}

```

```
Failed to run compilers on Arrays/arrays.js, Couldn't find preset "react-app" relative to directory "Arrays" 
    at C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19 
    at Array.map (<anonymous>) 
    at OptionManager.resolvePresets (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20) 
    at OptionManager.mergePresets (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10) 
    at OptionManager.mergeOptions (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14) 
    at OptionManager.init (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12) 
    at File.initOptions (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\index.js:212:65) 
    at new File (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\file\index.js:135:24) 
    at Pipeline.transform (C:\Users\Adhik\.quokka\node_modules\babel-core\lib\transformation\pipeline.js:46:16) 
    at processTicksAndRejections (internal/process/task_queues.js:75:11) 
```

Visual Studio Code v1.54.3

Windows

**Comment by ArtemGovorov** [comment]
> So, to work with vanilla JS projects in the future, do I have to always change the config file to work with vanilla JS?

You have configured Quokka to use Babel in your global config, so in this case the tool will try to use it for all projects. 
What you may do instead to avoid it, is to configure Quokka to use Babel only for project(s) that need Babel using Quokka [project config](https://quokkajs.com/docs/configuration.html).
