### ISSUE TITLE
quokka jetbrains plugin causes ide to freeze

### ISSUE THREAD

**Issue by rxliuli** [wallabyjs/quokka#610]
### Issue description or question

> jetbrains official information: https://intellij-support.jetbrains.com/hc/zh-cn/requests/3186946

When using webstorm and wallaby.js for unit testing, it is easy to get stuck in the IDE. After reporting the performance problem to jetbrains official, they found the problem with the quokka plugin. In fact, since the quokka plugin was disabled It is true that there have been no more stuck problems, please check and repair, this is fatal. . .

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

http://github.com/rxliuli/algorithm/

### Quokka.js Console Output

```
    at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.wallaby.javascript.WallabyController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.wallaby.javascript.WallabyController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
```

### Code editor version

Webstorm v? WS-203.7148.54

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
> https://intellij-support.jetbrains.com/hc/zh-cn/requests/3186946

Unfortunately we don't have access to the URL page. Can you please copy/paste the full discussion with the JetBrains team in this issue?

**Comment by rxliuli** [comment]
Rxliuli
2021 年 03 月 15 日 08:25
How do you rate the product?
3
Have you experienced any problems with WebStorm?
true
Problems
Performance problems
Please describe the problem in more detail. We’ll do our best to help.
Recently, it is easy to freeze after 2020.2, sometimes when opening the IDE to scan, sometimes opening a new project in a new window, or even sometimes editing the typescript code and it is directly stuck. This kind of problem often occurs, and I don't tire of it. . . Do I want to send webstorm logs to you? > It should not be a PC performance problem, my computer has 64G RAM
What technologies do you use in your current project(s)?
ECMAScript 6
TypeScript
Node.js
React
Vue.js
npm
Jest

---

Lejia Chen
2021 年 03 月 16 日 10:46
Hi,

Recently, it is easy to freeze after 2020.2, sometimes when opening the IDE to scan, sometimes opening a new project in a new window, or even sometimes editing the typescript code and it is directly stuck. This kind of problem often occurs, and I don't tire of it. . . Do I want to send webstorm logs to you? > It should not be a PC performance problem, my computer has 64G RAM

Could you please provide us with the WebStorm logs from IDE main menu Help | Collect Logs and Diagnostic Data for investigating?

Best Regards
Lejia Chen
JetBrains Support

---

Lejia Chen
2021 年 03 月 16 日 02:59
Please try to disable the Codota plugin in your WebStorm and restart the WebStorm to see if it helps.

Best Regards
Lejia Chen
JetBrains Support

---

Rxliuli
2021 年 03 月 16 日 04:11
ok, I will continue to give feedback if it appears again within a week

---

Rxliuli
2021 年 03 月 19 日 01:43
I have encountered this problem again today. I suddenly stranched when I wrote the code, then the IDE lost response forced me to close it in the task manager.

[webstorm-logs-20210319-134018.zip](https://github.com/wallabyjs/quokka/files/6234317/webstorm-logs-20210319-134018.zip)

---

Lejia Chen
2021 年 03 月 19 日 02:16
From your log, the Quokka plugin is the root cause of that long freezes.
Please also disable the Quokka plugin.

Best Regards
Lejia Chen
JetBrains Support

---

Rxliuli
2021 年 03 月 19 日 02:21
Ok, I will disable the Quokka plugin, but will continue to retain this problem. If there is no appearance in a week, I will turn off it.
In addition, I suspect that it is a problem with the Wallaby plugin. It is developed with the Quokka plugin. I use WALLABY to make a lot of unit tests.

---

Lejia Chen
2021 年 03 月 19 日 02:33
In addition, I suspect that it is a problem with the Wallaby plugin. It is developed with the Quokka plugin. I use WALLABY to make a lot of unit tests.

Yes, you are right here. I see these two plugins (Quokka, Wallaby) looped in the freeze log, which cause this issue (see log in threadDumps-freeze-20210319-124453-WS-203.7717.59-EditorActionHandler.execute-113sec from your provided log):

```java
    at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.wallaby.javascript.WallabyController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.wallaby.javascript.WallabyController$a.doExecute(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$$Lambda$5326/0x0000000102622440.perform(Unknown Source)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
    at com.quokka.javascript.QuokkaController$a.doExecute(Unknown Source)
```

You could also try disabling the Wallaby plugin if disable the Quokka not work.

Ok, I will disable the Quokka plugin, but will continue to retain this problem. If there is no appearance in a week, I will turn off it.

Feel free to contact us if you experience this problem again.
In case of any issues with WebStorm in the future, you could reach out to us using the Help | Contact Support option from IDE main menu.

Best Regards
Lejia Chen
JetBrains Support

**Comment by rxliuli** [comment]
> > https://intellij-support.jetbrains.com/hc/zh-cn/requests/3186946
> 
> Unfortunately we don't have access to the URL page. Can you please copy/paste the full discussion with the JetBrains team in this issue?

Relevant records have been added, is there any progress? If necessary, it is recommended to register a jetbrains account to continue to communicate with jetbrains official under that question.

**Comment by smcenlly** [comment]
Thanks for providing us with the logs and other details. We were unable to reproduce the problem but believe that we have found what was causing the problem. Could you please download and install the latest version of both the Wallaby and Quokka extensions and it should work for you.

* Quokka `v1.0.290+`
* Wallaby `v1.0.214+`

**Comment by rxliuli** [comment]
I will try to reinstall the latest version of the quokka plugin. If there are no problems within a week, I will close this question

**Comment by smcenlly** [comment]
I'm going to close this issue as we haven't heard back. Assuming everything is working properly. If not, please let us know and we'll re-open the issue.
