### ISSUE TITLE
JSDOM-Error

### ISSUE THREAD

**Issue by kushal-Ambati** [wallabyjs/quokka#677]
### Issue description or question
In windows, after installing the global package {JSDOM}, showed in the terminal asking to install the package or docs to configure, after clicking the install package {jsdom-quokka-plugin}, the window global element works, but the prompt() and alert() function don't work showing an error

### Sample code

```javascript
// paste the code you are running here
const a = alert("Hello world!")
```
### Quokka.js Console Output

```
// paste your quokka console output here
Error: Not implemented: window.alert 
    at module.exports (C:\Users\abcas\.quokka\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17) 
    at C:\Users\abcas\.quokka\node_modules\jsdom\lib\jsdom\browser\Window.js:863:7 
    at D:\Akv\HTML Projects\Javascript\quokka.js:2:30 
    at Object.<anonymous> (D:\Akv\HTML Projects\Javascript\quokka.js:4:3) 
    at Object.<anonymous> (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\esm-wallaby\esm.js:1:277320) 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\esm-wallaby\esm.js:1:271145 
    at Generator.next (<anonymous>) 
    at Zu (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\esm-wallaby\esm.js:1:271539) 
    at al (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\esm-wallaby\esm.js:1:273774) 
    at Object.<anonymous> (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\esm-wallaby\esm.js:1:275693) 
    at Object.<anonymous> (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:9741) 
    at n (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:1137) 
    at Object.next (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:432) 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:331 
    at new Promise (<anonymous>) 
    at _d0d‍.r.__awaiter (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:125) 
    at Object.quokkaStackTraceMarker (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:9254) 
    at u.<anonymous> (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:9867) 
    at n (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:1137) 
    at Object.next (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:432) 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:331 
    at new Promise (<anonymous>) 
    at _d0d‍.r.__awaiter (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:125) 
    at u.quokkaStackTraceMarker [as _onStart] (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\runners\node\quokka@1.0.0\initializer.js:14:4353) 
    at n (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\server.js:27:17522) 
    at u.start (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\server.js:27:17880) 
    at C.in:run (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\server.js:21:20571) 
    at WebSocket.<anonymous> (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\server.js:21:17470) 
    at WebSocket.emit (events.js:400:28) 
    at WebSocket.emit (domain.js:470:12) 
    at Receiver.ontext (c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\ws\lib\WebSocket.js:841:10) 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\ws\lib\Receiver.js:536:18 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\ws\lib\Receiver.js:368:7 
    at c:\Users\abcas\.vscode\extensions\wallabyjs.quokka-vscode-1.0.398\dist\wallaby\node_modules\ws\lib\PerMessageDeflate.js:249:5 
    at afterWrite (internal/streams/writable.js:466:5) 
    at onwrite (internal/streams/writable.js:446:7) 
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3) 
    at Zlib.processCallback (zlib.js:608:8) undefined 
```

### Code editor version
Visual Studio Code v1.60

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
The behaviour is expected. Quokka runs in node and optionally uses JSDOM to simulate browser-like environment, and [JSDOM doesn't support alert](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L884).

**Comment by ArtemGovorov** [comment]
You may use `console.log` instead to print out values you need.
