### ISSUE TITLE
Not working in typescript files

### ISSUE THREAD

**Issue by loganpowell** [wallabyjs/quokka#716]
### Issue description or question

When I compile my typescript files and run quokka in the generated `.js` file, it works, but doesn't in the `.ts` version

Is this issue related to Quokka not outputting the expected results of your code?: 
Yes 

### Sample code

```javascript
import * as API from "./API"
import { jsonToGraphQLQuery, EnumType } from "json-to-graphql-query"


export const createNode = ({
    input,
    condition,
}: {
    input: API.CreateNodeInput
    condition?: API.ModelNodeConditionInput
}) => ({
    q_name: "createNode",
    __args: {
        input,
        condition,
    },
    id: true,
    status: true,
    type: true,
    createdAt: true,
    updatedAt: true,
    owner: true,
    assets: true
})

jsonToGraphQLQuery({
    mutation: createNode({
        input: {
            status: API.NodeStatus.DRAFT,
            type: API.NodeType.A_COURSE,
        },
    }),
}) //? 


```

### Sample repository link

https://github.com/loganpowell/COPE-client-utils

### Quokka.js Console Output

```
​​​​​Quokka PRO 'json_mutations.ts' (node: v14.16.0, TypeScript: v4.3.5, plugins: jsdom-quokka-plugin)​​​​
c:\Users\logan\.vscode\extensions\wallabyjs.quokka-vscode-1.0.422\dist\wallaby\runners\node\quokka@1.0.0\jsdomQuokkaPlugin.js: Emit skipped 
  ​​​​​at ​​​​​​​​getOutput​​​ ​./node_modules/ts-node/src/index.ts:812​
  ​​​​​at ​​​​​​​​Object.compile​​​ ​./node_modules/ts-node/src/index.ts:1111​
  ​​​​​at ​​​​​​​​Object.m._compile​​​ ​./node_modules/ts-node/src/index.ts:1224​
  ​​​​​at ​​​​​​​​Object.require.extensions.<computed> [as .js]​​​ ​./node_modules/ts-node/src/index.ts:1228​

```

### Code editor version

Visual Studio Code v1.62.2

### OS name and version

Windows

Node: 14.16

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo. 
- I can't find the sample file (`json_mutations.ts`) in the https://github.com/loganpowell/COPE-client-utils project. If I manually create it and run Quokka, it shows a different (expected) error that gets fixed by [configuring Quokka to use native ESM](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await).
- Does the code work when you run it via `ts-node` outside of Quokka, for example via `ts-node json_mutations.ts` or `node --loader ts-node/esm son_mutations.ts`?

**Comment by loganpowell** [comment]
This is what I get when I run those in terminal:

```
D:\projects\aws\amplify\COPE-client-utils\src\graphql (master -> origin)
λ ts-node json_mutations.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for D:\projects\aws\amplify\COPE-client-utils\src\graphql\json_mutations.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

D:\projects\aws\amplify\COPE-client-utils\src\graphql (master -> origin)
λ node --loader ts-node/esm json_mutations.ts
(node:10256) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:383
    throw new ERR_MODULE_NOT_FOUND(
          ^
Error: Cannot find module 'D:\projects\aws\amplify\COPE-client-utils\src\graphql\API' imported from D:\projects\aws\amplify\COPE-client-utils\src\graphql\json_mutations.ts
    at finalizeResolution (D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:383:11)
    at moduleResolve (D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:818:10)
    at Object.defaultResolve (D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:929:11)
    at D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\src\esm.ts:68:38
    at Generator.next (<anonymous>)
    at D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist\esm.js:4:12)
    at resolve (D:\projects\aws\amplify\COPE-client-utils\node_modules\ts-node\dist\esm.js:32:16)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
```

This is my `.quokka` file content:

```
{
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "ts": {
    "compilerOptions": {
      "noEmitOnError": false
    }
  },
  "stdEsm": false,
  "nativeEsm": true
}
```

**Comment by ArtemGovorov** [comment]
> Error: Cannot find module 'D:\projects\aws\amplify\COPE-client-utils\src\graphql\API' imported from D:\projects\aws\amplify\COPE-client-utils\src\graphql\json_mutations.ts

Ok, so I'm getting the same issue when running Quokka on your file as you are getting from running your file with ts-node. If I add the `.js` extension to the import, then both `node --loader ts-node/esm json_mutations.ts` and Quokka start working for me (so the issue doesn't seem to be Quokka related):
![q716](https://user-images.githubusercontent.com/979966/142511575-6ab35dd0-b276-45a6-bd26-9029330b9a0d.gif)

**Comment by loganpowell** [comment]
I see. Thank you for looking into this @ArtemGovorov. Apologies for the mistake.
