### ISSUE TITLE
Quokka Generating Expected Output, but throwing TypeErrors in the process

### ISSUE THREAD

**Issue by zezang** [wallabyjs/quokka#798]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
function coinSum(num) {
    let comb = 0
    //check if a permutation yields a valid sum, if so increment counter by 1
    //base case is if num === 0, meaning we have subtracted enough values belonging to the valid array such that we have reached the num input
    if (num <= 1) return num;
    const valid = [1, 2, 5, 10, 20, 50, 100, 200];
    function sumCounter(remainder, index = 0) {
        if (remainder < 0) return;
        if (remainder === 0) {
          ++comb;
          return;
        }

        for (let i = index; i < valid.length; i++) {
        
            sumCounter(remainder - valid[i], i)
        }
        return comb
    }
    return sumCounter(num)
}

console.log(coinSum(7))
```
### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

**No file imports needed

### Quokka.js Console Output

```
Error: Uncaught [TypeError: mocha.setup is not a function] 
    at reportException (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24) 
    at processJavaScript (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7) 
    at HTMLScriptElementImpl._innerEval (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5) 
    at /Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:115:12 
    at ResourceQueue.push (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16) 
    at HTMLScriptElementImpl._fetchInternalScript (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:114:21) 
    at HTMLScriptElementImpl._eval (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:170:12) 
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:133:10) 
    at JSDOMParse5Adapter.onItemPop (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/html.js:175:43) 
    at Parser.onItemPop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:158:90) 
    at OpenElementStack.pop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/open-element-stack.js:89:22) 
    at endTagInText (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:2180:20) 
    at Parser._endTagOutsideForeignContent (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:858:17) 
    at Parser.onEndTag (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:831:18) 
    at Tokenizer.emitCurrentTagToken (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:403:26) 
    at Tokenizer.handleSpecialEndTag (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1158:22) 
    at Tokenizer._stateScriptDataEndTagName (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1246:18) 
    at Tokenizer._stateScriptDataEndTagOpen (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1235:18) 
    at Tokenizer._callState (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:624:22) 
    at Tokenizer._runParsingLoop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:227:22) 
    at Tokenizer.write (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:252:14) 
    at Parser.parse (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:101:26) 
    at Object.parse (/Users/zango/.quokka/node_modules/parse5/dist/cjs/index.js:41:30) 
    at parseIntoDocument (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/html.js:202:17) 
    at parseIntoDocument (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/index.js:31:10) 
    at new JSDOM (/Users/zango/.quokka/node_modules/jsdom/lib/api.js:42:5) 
    at beforeEach (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/jsdomQuokkaPlugin.js:14:1070) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:10074 
    at Array.forEach (<anonymous>) 
    at p.<anonymous> (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:10054) 
    at r (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:1137) 
    at Object.next (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:432) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:331 
    at new Promise (<anonymous>) 
    at _bf5‍.r.__awaiter (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:125) 
    at p.quokkaStackTraceMarker [as _onStart] (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:4457) 
    at r (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:28:26957) 
    at p.start (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:28:27315) 
    at in:run (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:22:20500) 
    at WebSocket.<anonymous> (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:22:17331) 
    at WebSocket.emit (node:events:537:28) 
    at WebSocket.emit (node:domain:482:12) 
    at Receiver.ontext (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/WebSocket.js:841:10) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/Receiver.js:536:18 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/Receiver.js:368:7 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5 
    at afterWrite (node:internal/streams/writable:500:5) 
    at onwrite (node:internal/streams/writable:480:7) 
    at Zlib.cb (node:internal/streams/transform:171:7) 
    at Zlib.processCallback (node:zlib:613:8) [TypeError: mocha.setup is not a function] 
 
Error: Uncaught [TypeError: mocha.globals is not a function] 
    at reportException (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24) 
    at processJavaScript (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7) 
    at HTMLScriptElementImpl._innerEval (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5) 
    at /Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:115:12 
    at ResourceQueue.push (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16) 
    at HTMLScriptElementImpl._fetchInternalScript (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:114:21) 
    at HTMLScriptElementImpl._eval (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:170:12) 
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:133:10) 
    at JSDOMParse5Adapter.onItemPop (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/html.js:175:43) 
    at Parser.onItemPop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:158:90) 
    at OpenElementStack.pop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/open-element-stack.js:89:22) 
    at endTagInText (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:2180:20) 
    at Parser._endTagOutsideForeignContent (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:858:17) 
    at Parser.onEndTag (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:831:18) 
    at Tokenizer.emitCurrentTagToken (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:403:26) 
    at Tokenizer.handleSpecialEndTag (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1158:22) 
    at Tokenizer._stateScriptDataEndTagName (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1246:18) 
    at Tokenizer._stateScriptDataEndTagOpen (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:1235:18) 
    at Tokenizer._callState (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:624:22) 
    at Tokenizer._runParsingLoop (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:227:22) 
    at Tokenizer.write (/Users/zango/.quokka/node_modules/parse5/dist/cjs/tokenizer/index.js:252:14) 
    at Parser.parse (/Users/zango/.quokka/node_modules/parse5/dist/cjs/parser/index.js:101:26) 
    at Object.parse (/Users/zango/.quokka/node_modules/parse5/dist/cjs/index.js:41:30) 
    at parseIntoDocument (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/html.js:202:17) 
    at parseIntoDocument (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/parser/index.js:31:10) 
    at new JSDOM (/Users/zango/.quokka/node_modules/jsdom/lib/api.js:42:5) 
    at beforeEach (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/jsdomQuokkaPlugin.js:14:1070) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:10074 
    at Array.forEach (<anonymous>) 
    at p.<anonymous> (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:10054) 
    at r (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:1137) 
    at Object.next (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:432) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:331 
    at new Promise (<anonymous>) 
    at _bf5‍.r.__awaiter (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:125) 
    at p.quokkaStackTraceMarker [as _onStart] (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:4457) 
    at r (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:28:26957) 
    at p.start (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:28:27315) 
    at in:run (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:22:20500) 
    at WebSocket.<anonymous> (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/server.js:22:17331) 
    at WebSocket.emit (node:events:537:28) 
    at WebSocket.emit (node:domain:482:12) 
    at Receiver.ontext (/Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/WebSocket.js:841:10) 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/Receiver.js:536:18 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/Receiver.js:368:7 
    at /Users/zango/.vscode/extensions/wallabyjs.quokka-vscode-1.0.487/dist/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5 
    at afterWrite (node:internal/streams/writable:500:5) 
    at onwrite (node:internal/streams/writable:480:7) 
    at Zlib.cb (node:internal/streams/transform:171:7) 
    at Zlib.processCallback (node:zlib:613:8) [TypeError: mocha.globals is not a function] 
 
Error: Uncaught [ReferenceError: loadScroll is not defined] 
    at reportException (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24) 
    at innerInvokeEventListeners (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9) 
    at invokeEventListeners (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3) 
    at EventTargetImpl._dispatch (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9) 
    at fireAnEvent (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36) 
    at Document.<anonymous> (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/Window.js:917:9) 
    at Document.callTheUserObjectsOperation (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30) 
    at innerInvokeEventListeners (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25) 
    at invokeEventListeners (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3) 
    at DocumentImpl._dispatch (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9) 
    at fireAnEvent (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36) 
    at dispatchEvent (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:472:9) 
    at /Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:477:11 
    at new Promise (<anonymous>) 
    at onLoad (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:475:14) 
    at Object.check (/Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23) 
    at /Users/zango/.quokka/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:83:27 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) [ReferenceError: loadScroll is not defined] 

6 ​​​​​at ​​​​​​​​coinSum(7)​​​ ​part2/coinSum.js:49:1​

2 ​​​​​at ​​​​​​​​coinSum(2)​​​ ​part2/coinSum.js:88:1​
```

### Code editor version

Visual Studio Code v1.69.0 (Universal)

### OS name and version

macOS Monterey
Version 12.4

![Screen Shot 2022-07-09 at 9 49 36 PM](https://user-images.githubusercontent.com/97820794/178131756-db9ae04f-7e5e-446f-b7b8-9cabd814c8f2.png)
![Screen Shot 2022-07-09 at 9 50 03 PM](https://user-images.githubusercontent.com/97820794/178131761-13c19f11-9687-4de3-b81e-e046b928edb7.png)
![Screen Shot 2022-07-09 at 9 50 18 PM](https://user-images.githubusercontent.com/97820794/178131765-ef2086a8-251f-4d07-a5a8-302d0b4af0d7.png)

**Comment by smcenlly** [comment]
Could you please provide us with your Quokka configuration (global and project-level configuration files)?

It looks like your configuration is causing a problem because the same code snippet works on a fresh Quokka install. You may try resetting your Quokka installation by deleting your `~/.quokka` folder from your home directory. After doing so, please close/re-open VS Code. You may need to reapply your license after deleting the `~/.quokka` folder but then Quokka should work for you.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Assuming our suggetsion worked for you. If you're still having problems, please reply and we will reopen the issue.

**Comment by zezang** [comment]
Sorry I didn't respond sooner. Yes, the issue is resolved. Just so there's a record of how the problem was fixed, I completely uninstalled VS Code and re-installed it along with all quokka and that fixed the issue.
