### ISSUE TITLE
ReferenceError quokkaFilename is not defined and TypeError: Cannot read properties of undefined (reading 'close')

### ISSUE THREAD

**Issue by SimonSiefke** [wallabyjs/quokka#801]
### Issue description or question

I tried to uninstall and reinstall the quokka extension due to https://github.com/wallabyjs/quokka/issues/800, but now it seems to be even more broken: 
- The output pane doesn't open anymore
- In chrome devtools, it shows an error `ReferenceError quokkaFilename is not defined`
- In chrome devtools, it shows an error `TypeError: Cannot read properties of undefined (reading 'close')`

[Screencast from 17.07.2022 11:16:00.webm](https://user-images.githubusercontent.com/23744935/179391936-7d6c725d-c395-467e-95ff-47db44c2fe89.webm)

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
const add = (a, b) => {
  return a + b;
};

add(1, 2); //?
```

### Quokka.js Console Output

Nothing

### Errors

Error 1:
```
workbench.desktop.main.js:2272 ReferenceError: quokkaFilename is not defined
	at vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:4849
	at ChildProcess.<anonymous> (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:4248)
	at ChildProcess.emit (node:events:390:28)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
	at onErrorNT (node:internal/child_process:477:16)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Error 2:
```
workbench.desktop.main.js:2272 [[object Object]]Cannot read properties of undefined (reading 'close')
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2272 TypeError: Cannot read properties of undefined (reading 'close')
	at f.<anonymous> (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:5667)
	at r (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:1560)
	at Object.next (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:855)
	at vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:764
	at new Promise (<anonymous>)
	at r (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:558)
	at f.stop (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/client.js:14:5442)
	at Object.dispose (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:56622)
	at vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:13075
	at Array.forEach (<anonymous>)
	at t.exports.dispose (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:13062)
	at P._stop (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:45348)
	at vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:37780
	at Array.forEach (<anonymous>)
	at P.stopAll (vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:37764)
	at vscode-file://vscode-app/home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/index.js:6:15585
	at o._executeContributedCommand (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at w.invoke (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at w.invoke (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at w.invoke (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at Socket.R (vscode-file://vscode-app/snap/code/101/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

### Code editor version

Visual Studio Code v1.69.1

### OS name and version
Ubuntu 22.04

**Comment by smcenlly** [comment]
Did you also uninstall/reinstall VS Code?

It looks like you have installed VS Code using `snap`. There are various known issues (unrelated to Quokka) using snap that may occur as a result of snap sandboxing. Without custom flags at installation, or subsequent interface connections, snaps are confined to a restrictive security sandbox with no access to system resources outside of the snap which means that Quokka cannot run. You will find other extensions that spawn child processes are affected in a similar way.

Please uninstall VS Code (via `snap`) and then install VS Code via the [Microsoft download](https://code.visualstudio.com). It should work for you.

**Comment by smcenlly** [comment]
We found another problem that may also be causing your issue. You may also try updating to `Quokka v1.0.491` to try and fix your problem.
