### ISSUE TITLE
Quokka don't start - with the "Can not start node.js proces" popup message.

### ISSUE THREAD

**Issue by garbolovo** [wallabyjs/quokka#818]
### Issue description or question

Can not start node.js process (/usr/local/bin/node).  You may use the "node" setting to configure the location of node.

## Please, advise what is going on and solve the issue !

WebStorm 2021.1.3
Build #WS-211.7628.25, built on June 30, 2021

macOS 12.4
![Screenshot 2022-09-28 at 12 49 18 AM](https://user-images.githubusercontent.com/50718692/192642729-d7254f8b-fd03-44d0-9213-979ca5f2f6a9.jpg)
![Screenshot 2022-09-28 at 12 47 31 AM](https://user-images.githubusercontent.com/50718692/192642737-06f2cdcd-5bce-4ec9-97bb-dddaaa027dd9.jpg)
![Screenshot 2022-09-28 at 1 06 09 AM](https://user-images.githubusercontent.com/50718692/192646142-394d3bf8-60fa-43ed-9b00-37738e264f87.jpg)

**Comment by smcenlly** [comment]
Could you please provide us with your WebStorm log after receiving the error? It's available from the WebStorm menu, `Help -> Show Log in Finder`.

The log should have some additional information to help us troubleshoot.

**Comment by garbolovo** [comment]
`2022-09-28 02:46:59,845 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2022-09-28 02:46:59,853 [      8]   INFO - llij.ide.gdpr.EndUserAgreement - eua: /Users/aleksei/Library/Application Support/JetBrains/PrivacyPolicy/eua.cached 
2022-09-28 02:46:59,872 [     27]   INFO - .intellij.util.EnvironmentUtil - loading shell env: /bin/zsh -l -i -c '/Applications/WebStorm.app/Contents/bin/printenv.py' '/var/folders/1l/8nnjl6ms065b28x4bsx0tlsc0000gq/T/intellij-shell-env.7605672275415647674.tmp' 
2022-09-28 02:46:59,911 [     66]   INFO -        #com.intellij.idea.Main - IDE: WebStorm (build #WS-211.7628.25, 30 Jun 2021 13:17) 
2022-09-28 02:46:59,914 [     69]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (12.4, x86_64) 
2022-09-28 02:46:59,924 [     79]   INFO -        #com.intellij.idea.Main - JRE: 11.0.11+9-b1341.60 (JetBrains s.r.o.) 
2022-09-28 02:46:59,924 [     79]   INFO -        #com.intellij.idea.Main - JVM: 11.0.11+9-b1341.60 (OpenJDK 64-Bit Server VM) 
2022-09-28 02:46:59,931 [     86]   INFO -        #com.intellij.idea.Main - JVM Args: -Xmx2048m -Djb.vmOptionsFile=/Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1/webstorm.vmoptions -Didea.paths.selector=WebStorm2021.1 -Didea.executable=webstorm -Didea.platform.prefix=WebStorm -Didea.vendor.name=JetBrains -Didea.home.path=/Applications/WebStorm.app/Contents 
2022-09-28 02:46:59,931 [     86]   INFO -        #com.intellij.idea.Main - library path: /Users/aleksei/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. 
2022-09-28 02:46:59,931 [     86]   INFO -        #com.intellij.idea.Main - boot library path: /Applications/WebStorm.app/Contents/jbr/Contents/Home/lib 
2022-09-28 02:46:59,962 [    117]   INFO -        #com.intellij.idea.Main - locale=en_GB JNU=UTF-8 file.encoding=UTF-8
  idea.config.path=/Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1
  idea.system.path=/Users/aleksei/Library/Caches/JetBrains/WebStorm2021.1
  idea.plugins.path=/Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1/plugins
  idea.log.path=/Users/aleksei/Library/Logs/JetBrains/WebStorm2021.1 
2022-09-28 02:47:00,086 [    241]   WARN - .intellij.util.EnvironmentUtil - can't get shell environment 
java.io.IOException: command [/bin/zsh, -l, -i, -c, '/Applications/WebStorm.app/Contents/bin/printenv.py' '/var/folders/1l/8nnjl6ms065b28x4bsx0tlsc0000gq/T/intellij-shell-env.7605672275415647674.tmp']
	exit code:127 text:0 out:env: python: No such file or directory
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadOutputAndEnvs(EnvironmentUtil.java:335)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadOutputAndEnvs(EnvironmentUtil.java:294)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.doReadShellEnv(EnvironmentUtil.java:253)
	at com.intellij.util.EnvironmentUtil.getShellEnv(EnvironmentUtil.java:203)
	at com.intellij.util.EnvironmentUtil.lambda$loadEnvironment$0(EnvironmentUtil.java:110)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-09-28 02:47:00,778 [    933]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 791 ms 
2022-09-28 02:47:01,568 [   1723]   INFO - ntellij.idea.ApplicationLoader - CPU cores: 16; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@7e99a5d9[Running, parallelism = 15, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@6398a7f9 
2022-09-28 02:47:01,600 [   1755]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: IDEA CORE (211.7628.25), com.intellij.platform.images (211.7628.25), HTML Tools (211.7628.25), Refactor-X (211.7628.25), Subversion (211.7628.25), XPathView + XSLT (211.7628.25), IDE Settings Sync (211.7628.25), Machine Learning Code Completion (211.7628.25), Configuration Script (211.7628.25), Copyright (211.7628.25), Diagrams (211.7628.25), Java Server Pages (JSP) (211.7628.25), macOS Light Theme (211.7628.25), Task Management (211.7628.25), Time Tracking (211.7628.25), Performance Testing (211.7628.25), Shared Indexes (211.7628.25), FTP/SFTP Connectivity (ex. Remote Hosts Access) (211.7628.25), File Watchers (211.7628.25), CSS (211.7628.25), W3C Validators (211.7628.25), Less (211.7628.25), Sass (211.7628.25), Stylus (211.7628.25), Mercurial (211.7628.25), WebP Support (211.7628.25), EditorConfig (211.7628.25), Haml (211.7628.25), Terminal (211.7628.25), Git (211.7628.25), ChangeReminder (211.7628.25), GitHub (211.7628.25), Project Shared Indexes (211.7628.25), SSH Remote Run (211.7628.25), Shell Script (211.7628.25), TextMate Bundles (211.7628.25), Vagrant (211.7628.25), YAML (211.7628.25), Docker (211.7628.25), Settings Repository (211.7628.25), IDE Features Trainer (211.7628.25), IntelliLang (211.7628.25), Gherkin (211.7628.25), Markdown (211.7628.25), Grazie (211.7628.25), JavaScript and TypeScript (211.7628.25), JavaScript Intention Power Pack (211.7628.25), JavaScript Debugger (211.7628.25), Node.js (211.7628.25), Node.js Remote Interpreter (211.7628.25), Live Edit (211.7628.25), Spy-js (211.7628.25), Karma (211.7628.25), Styled Components & Styled JSX (211.7628.25), Polymer & Web Components (211.7628.25), Tailwind CSS (211.7628.25), EJS (211.7628.25), Pug (ex-Jade) (211.7628.25), Cucumber.js (211.7628.25), Prettier (211.7628.25), CoffeeScript (211.7628.25), Vue.js (211.7628.25), TSLint (211.7628.25), Angular and AngularJS (211.7628.25), Handlebars/Mustache (211.7628.25), Meteor (211.7628.25), Cordova (211.7628.25), HTTP Client (211.7628.25) 
2022-09-28 02:47:01,600 [   1755]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: HighlightBracketPair (1.3.6), Gray Theme (1.3), Green lite theme (0.1.2), Visual Studio Code Dark Plus Theme (2.6), Dracula Theme (1.13.3), Quokka (1.0.341) 
2022-09-28 02:47:01,600 [   1755]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Code With Me (211.7628.25), Database Tools and SQL for WebStorm (211.7628.16) 
2022-09-28 02:47:01,797 [   1952]   INFO - m.intellij.util.io.StorageLock - lower=100; upper=500; buffer=10; max=2028 
2022-09-28 02:47:01,819 [   1974]   INFO - tellij.util.io.FileChannelUtil - uninterruptible FileChannels will be used for indexes 
2022-09-28 02:47:01,835 [   1990]   INFO - ication.options.PathMacrosImpl - Loaded path macros: {} 
2022-09-28 02:47:01,915 [   2070]   INFO - intellij.diagnostic.JitWatcher - JIT compilation state checking enabled 
2022-09-28 02:47:01,949 [   2104]   INFO - m.intellij.ui.mac.touchbar.NST - nst library works properly, successfully created and released native touchbar object 
2022-09-28 02:47:01,952 [   2107]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2022-09-28 02:47:01,959 [   2114]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2022-09-28 02:47:02,075 [   2230]   INFO - cloudConfig.CloudConfigManager - === Start: JBA_NOT_CONNECTED (1ms) === 
2022-09-28 02:47:02,107 [   2262]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2022-09-28 02:47:02,170 [   2325]   WARN - rationStore.ComponentStoreImpl - Duplicated scheme Visual Studio Code Dark Plus - old: Visual Studio Code Dark Plus, new Visual Studio Code Dark Plus 
2022-09-28 02:47:02,257 [   2412]   INFO - impl.SharedIndexMainZipStorage - Shared Indexes Storage is opened: <empty>, chunks: [] 
2022-09-28 02:47:02,321 [   2476]   INFO - cloudConfig.CloudConfigManager - === Start.updateInitStatus === 
2022-09-28 02:47:02,333 [   2488]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus === 
2022-09-28 02:47:03,297 [   3452]   INFO - leBasedIndexDataInitialization - Index data initialization done: 1252 ms. Initialized indexes: [FilenameIndex, filetypes, TodoIndex, IdIndex, FrameworkDetectionIndex, DomFileIndex, Trigram.Index, XmlTagNames, RelaxSymbolIndex, XmlNamespaces, html5.custom.attributes.index, SchemaTypeInheritance, json.file.root.values, HtmlTagIdIndex, HashFragmentIndex, XsltSymbolIndex, fileIncludes, CompassFunctionsIndex, editorconfig.index.name, yaml.keys.name, docker.compose.services, js.test.names, js.package.index, js.custom.single.entry.index, css.template.selectors, CssIndex, js.implicit.elements.index, js.string.literal.words.index, TypeScriptExternalPathCandidates, WebComponentsIndex, angularjs.template.cache, VueNoScriptFilesIndex, angularjs.ui.router.views.index, angularjs.app.index, MeteorTemplateIndex, http.request.execution.environment, http.request.completion.host, http.request.headers.values.index, Stubs]. 
2022-09-28 02:47:03,329 [   3484]   INFO - exImpl$StubIndexInitialization - Index data initialization done: 31 ms. Initialized stub indexes: {JS.class.implements, vue.global.filters.index, js.local.namespace.members.index, Stylus.variables, angularjs.ui.router.states.index, es6.assignment.index, angular2.metadata.function.index, angular2.metadata.module.index, js.imported.bindings.index, JS.custom.stub.index, JS.class.super, angularjs.ui.router.generic.states.index, angularjs.symbol.index, JS.subclass.stub.index, angular2.ivy.directive.index, angular2.source.module.index, angular2.ivy.pipe.index, js.namespace.index, angular2.source.directive.index, angularjs.directives.index, angularjs.filter.index, angularjs.templateUrl.index, js.symbol.qualified.names.index, js.doc.modules, vue.url.index, ts.local.classes, es6.exported.index, js.exported.index, ts.embedded.content.index, vuex.store.index, angularjs.directives.doc.index, vue.global.directives.index, js.gcl.modules, vue.id.index, vue.mixin.binding.index, vue.options.index, js.amd.modules, vue.components.index, jade.mixin, js.generics.index, vue.extends.binding.index, dom.elementClass, amd.requirePaths.index, js.lazy.packages, angular2.metadata.className.index, js.nonglobal.symbol.index, js.global.symbol.index, angularjs.module.index, angularjs.controller.index, js.element.qualifiedName, js.qualified.shortName, JS.global.qualified.elements, js.typedef.index2, angularjs.generic.modules.index, angular2.metadata.pipe.index, amd.baseUrl.index, angular2.ivy.module.index, angular2.source.pipe.index, angularjs.delimiter.index, angular2.templateUrl.index, js.class.index2, JS.base.types.index, js.symbol.index2, ts.external.module.index, Scss.function, angular2.metadata.directive.index, angular2.metadata.node.index, Stylus.mixins, markdown.header, Less.variables, Less.mixins, Css.custom.property, Scss.placeholder.selector, Scss.mixin, dom.namespaceKey, Css.ampersand.selector, Css.attr, Css.custom.mixin, Css.class, Scss.variable, Css.id}. 
2022-09-28 02:47:04,276 [   4431]   INFO - nfig.ETagCloudConfigFileClient - === Get cloud config URL: https://cloudconfig.jetbrains.com/cloudconfig/files === 
2022-09-28 02:47:05,628 [   5783]   INFO - cloudConfig.CloudConfigManager - === calculateInitStatus.value: JBA_NOT_CONNECTED === 
2022-09-28 02:47:05,630 [   5785]   INFO - cloudConfig.CloudConfigManager - === End.updateInitStatus === 
2022-09-28 02:47:06,055 [   6210]   INFO - BridgeProjectLifecycleListener - Using workspace model to open project 
2022-09-28 02:47:06,138 [   6293]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/WebStorm.app/Contents/bin/fsnotifier 
2022-09-28 02:47:06,142 [   6297]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2022-09-28 02:47:06,185 [   6340]   INFO - rojectCodeStyleSettingsManager - Loading Project code style 
2022-09-28 02:47:06,441 [   6596]   INFO - el.ide.impl.WorkspaceModelImpl - Load workspace model from cache in 227 ms 
2022-09-28 02:47:06,650 [   6805]   INFO - al.NewToolbarRootPaneExtension - ToolbarSettingsService is ExperimentalToolbarSettings 
2022-09-28 02:47:06,650 [   6805]   INFO - al.NewToolbarRootPaneExtension - Show new toolbar: false, presentation mode: false 
2022-09-28 02:47:06,650 [   6805]   INFO - al.NewToolbarRootPaneExtension - Show old main toolbar: false, old navbar visible: true 
2022-09-28 02:47:06,806 [   6961]   INFO - al.NewToolbarRootPaneExtension - ToolbarSettingsService is ExperimentalToolbarSettings 
2022-09-28 02:47:06,806 [   6961]   INFO - al.NewToolbarRootPaneExtension - Show new toolbar: false, presentation mode: false 
2022-09-28 02:47:06,806 [   6961]   INFO - al.NewToolbarRootPaneExtension - Show old main toolbar: false, old navbar visible: true 
2022-09-28 02:47:07,769 [   7924]   INFO - tellij.xml.Html5SchemaProvider - CHARS_DTD_LOCATION = /Applications/WebStorm.app/Contents/lib/intellij-xml.jar!/resources/html5-schema/html5chars.ent 
2022-09-28 02:47:07,803 [   7958]   INFO - penapi.application.Experiments - Experimental features enabled for user: wsl.p9.support, wsl.prefer.p9.support, wsl.p9.show.roots.in.file.chooser, wsl.execute.with.wsl.exe, inline.browse.button, linux.native.menu, recent.and.edited.files.together, show.create.new.element.in.popup, search.everywhere.mixed.results, i18n.match.actions, editor.reader.mode, edit.run.configurations.while.dumb, new.large.text.file.viewer, terminal.shell.command.handling, reuse.target.paths.for.rsync 
2022-09-28 02:47:08,230 [   8385]   INFO -              PerformancePlugin - Performance Plugin is in silent mode 
2022-09-28 02:47:09,309 [   9464]   INFO - ion.DelayedProjectSynchronizer - Workspace model loaded from cache. Syncing real project state into workspace model in 1046 ms. Thread[ApplicationImpl pooled thread 15,4,Idea Thread Group] 
2022-09-28 02:47:09,429 [   9584]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 4 millis (read time: 1) 
2022-09-28 02:47:09,564 [   9719]   INFO - redIndexChunkConfigurationImpl - Chunk bundled-js-predefined-ffdd448c697d-b21cf67d8133-JavaScript-WS-211.7628.25 is registered for project 'myjs: matching: (fb=36, stub=81), incompatible: (fb=0, stub=0), unknown: (fb=9, stub=9),  
2022-09-28 02:47:09,610 [   9765]   INFO - indexing.UnindexedFilesUpdater - Started 
2022-09-28 02:47:09,663 [   9818]   INFO - indexing.UnindexedFilesUpdater - Scanning: use 15 scanning threads 
2022-09-28 02:47:09,672 [   9827]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2022-09-28 02:47:09,692 [   9847]   INFO - al.NewToolbarRootPaneExtension - ToolbarSettingsService is ExperimentalToolbarSettings 
2022-09-28 02:47:09,693 [   9848]   INFO - al.NewToolbarRootPaneExtension - Show new toolbar: false, presentation mode: false 
2022-09-28 02:47:09,693 [   9848]   INFO - al.NewToolbarRootPaneExtension - Show old main toolbar: false, old navbar visible: true 
2022-09-28 02:47:09,849 [  10004]   INFO - SharedIndexPostStartupActivity - Attached 1 pre-built shared indexes: bundled-js-predefined-ffdd448c697d-b21cf67d8133-JavaScript-WS-211.7628.25 
2022-09-28 02:47:09,905 [  10060]   INFO - ProjectRootPostStartUpActivity - /Users/aleksei/WebstormProjects/myjs/.idea case-sensitivity: expected=false actual=false 
2022-09-28 02:47:09,914 [  10069]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2022-09-28 02:47:09,922 [  10077]   INFO - oudConfig.StatusBarInfoManager - === StatusBar.start create === 
2022-09-28 02:47:09,933 [  10088]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 1676ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2022-09-28 02:47:10,089 [  10244]   INFO - indexing.UnindexedFilesUpdater - Scanning completed. Number of scanned files: 367; Number of files for indexing: 0 took 479ms; general responsiveness: ok; EDT responsiveness: ok 
2022-09-28 02:47:10,094 [  10249]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 4048 ms 
2022-09-28 02:47:10,100 [  10255]   INFO - indexing.UnindexedFilesUpdater - Pushing properties took 11ms; general responsiveness: ok; EDT responsiveness: ok 
2022-09-28 02:47:10,103 [  10258]   INFO - indexing.UnindexedFilesUpdater - Finish. No files to index with loading content. 
2022-09-28 02:47:11,175 [  11330]   INFO - tellij.xml.Html5SchemaProvider - HTML5_SCHEMA_LOCATION = /Applications/WebStorm.app/Contents/lib/intellij-xml.jar!/resources/html5-schema/html5.rnc 
2022-09-28 02:47:16,351 [  16506]   WARN -                         Quokka - Quokka core path: /Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1/plugins/quokka-intellij/dist/server.js 
2022-09-28 02:47:25,140 [  25295]   INFO - ication.options.PathMacrosImpl - Saved path macros: {} 
`

**Comment by smcenlly** [comment]
Can you please email the following files from your user home directory to hello@wallabyjs.com

* `~/.quokka/config.json`
* `~/.quokka/.qid`
* `~/.quokka/.qlc`
* `~/.wallaby/.key.lic`
* `~/.wallaby/.ol`

We will assume that the file did not exist if it is missing for your email.

**Comment by garbolovo** [comment]
[q-email.zip](https://github.com/wallabyjs/quokka/files/9663425/q-email.zip)

sent it to email and attached here, only three of them as  my  ~/.wallaby/ is empty.

**Comment by garbolovo** [comment]
![Uploading Screenshot 2022-09-28 at 6.05.10 PM.jpg…]()

**Comment by garbolovo** [comment]
![Screenshot 2022-09-28 at 6 05 10 PM](https://user-images.githubusercontent.com/50718692/192832664-6c06d5dc-2243-492d-9a7f-a42bdc66d21b.jpg)

**Comment by garbolovo** [comment]
PLease, see comment above.

**Comment by smcenlly** [comment]
Thanks for the additional information.

Could you please check whether the `server.js` file exists in the location referenced in the error message?

If it does not, please try uninstalling and reinstalling Quokka as perhaps your installation become corrupted somehow.

**Comment by smcenlly** [comment]
@garbolovo - were you able to get it working? If not, can you please check whether the `server.js` file exists in the location referenced in the error message?

If it does not, please try uninstalling and reinstalling Quokka as perhaps your installation become corrupted somehow.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back.

**Comment by garbolovo** [comment]
<img width="638" alt="Screenshot 2023-03-10 at 01 20 26" src="https://user-images.githubusercontent.com/50718692/224173350-2a2fb919-8971-4ebd-890c-2c1ef569bff9.png">

I did not see any server.js files
what should I do next ?

**Comment by smcenlly** [comment]
As per [our message above](https://github.com/wallabyjs/quokka/issues/818#issuecomment-1261547054), You will need to check for `server.js` file exists in the location referenced in the error message: `/Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1/plugins/quokka-intellij/dist/server.js` (please copy/paste from the error message)

Did you try uninstalling and reinstalling Quokka?

**Comment by garbolovo** [comment]
Thanks for your reply, I will get with the answer later as at the moment I  can't check.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Please check for `server.js` file in the location referenced in the error message: `/Users/aleksei/Library/Application Support/JetBrains/WebStorm2021.1/plugins/quokka-intellij/dist/server.js` (please copy/paste from the error message).

Please also try uninstalling and reinstalling Quokka.
