### ISSUE TITLE
quokka throws error with for an esm only library

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#855]
### Issue description or question

I am facing an issue when I am using quokka with [modern-errors](https://github.com/ehmicky/modern-errors). It runs fine with node cli. These library is `esm only` library

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
import ModernError from "modern-errors";

export const InvalidInputError = ModernError.subclass('InvalidInputError', {
    custom: class extends ModernError {
        #schemaId;
        constructor(message, options, schemaId) {
            super(message, options);
            this.#schemaId = schemaId;
        }
        get schemaId() {return this.#schemaId}
    }
})

const error = new InvalidInputError('Wrong user name', {}, "schema/1.0.0")

console.log(`error.message`, error.schemaId);
```

### Sample repository link

[bhvngt/modern-error-quokka](https://github.com/bhvngt/modern-error-quokka)

### Quokka.js Console Output

```
test.js (node: v18.13.0)

"new InvalidInputError()" must not be directly called.
This error class should be created like this instead:
  export const InvalidInputError = custom.subclass('InvalidInputError')
	at validateSubclass ./node_modules/.pnpm/modern-errors@5.5.0/node_modules/modern-errors/build/src/subclass/validate.js:21
	at new ModernError ./node_modules/.pnpm/modern-errors@5.5.0/node_modules/modern-errors/build/src/main.js:26
	at new custom src/test.js:7:12
	at new InvalidInputError ./node_modules/.pnpm/modern-errors@5.5.0/node_modules/modern-errors/build/src/subclass/custom.js:21
	at src/test.js:14:0

```

### Code editor version

Intellij: 2022.3.1

### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We have found and fixed the issue.

Please update to the latest version of Quokka, it should now work for you.
