### ISSUE TITLE
Quokka on Windows with WSL not working with latest version of WebStorm

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#896]
windows 11 x64, wsl2

Webstorm output:
```
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
	at com.quokka.javascript.session.QuokkaSession.O(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
_config.json_
```json{
  "pro":true,
  "useWsl":true,
  "node":"/home/oliver/.nvm/versions/node/v16.20.2/bin/node"
}
```

**but qokka works fine with vscode**

_Originally posted by @OliverMax in https://github.com/wallabyjs/quokka/issues/65#issuecomment-1722267890_

**Comment by smcenlly** [comment]
The latest version of WebStorm has introduced a delay in the automated port mapping between your WSL instance and your Windows machine. This causes Quokka to fail to connect to your WSL instance. We're not sure the reason for this change, but we have updated the latest version of Quokka to fix the problem.

Please update your [Quokka editor plugin](https://plugins.jetbrains.com/plugin/9667-quokka) to `v1.0.395+`, it should fix your problem.

If you're still having problems, please let us know.
