### ISSUE TITLE
(Quokka Stopped Working) Language Log is not supported

### ISSUE THREAD

**Issue by russgooday** [wallabyjs/quokka#972]
### Quokka doesn't work at all

Is this issue related to Quokka not outputting the expected results of your code?: Yes
Quokka 1.0.640 Not starting at all on any code.

In toggle developer console
```
   [Extension Host] TypeError: Cannot read properties of undefined (reading 'filename')
    at I._start (c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:59433)
    at I._runFromExistingFile (c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:49519)
    at c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:37437
    at I._runIfAllowed (c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:50125)
    at I.makeQuokkaFromExistingFile (c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:37414)
    at c:\Users\redacted\.vscode\extensions\wallabyjs.quokka-vscode-1.0.640\dist\index.js:6:15463
    at Y0.h (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
    at Y0.$executeContributedCommand (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
    at py.S (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111285)
    at mh.value (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
    at D.B (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/redacted/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

### Quokka.js Console Output

```
Language Log is not supported
```

### Code editor version

Visual Studio Code v1.95?

### OS name and version

Windows 11

**Comment by smcenlly** [comment]
In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code; there is nothing we can do to fix this for previous versions. 

---

If you have an expired license, you have a number of options available to you:

1. Use the older version of VS Code; [Microsoft docs](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates) describe how to use the previous version:

> You can install a previous release of VS Code by uninstalling your current version and then installing the download provided at the top of a specific release notes page.

2. Use the latest version of Quokka and switch to use Community Edition.
3. Use the latest version of Quokka and renew your license to continue using PRO features.

Unfortunately, we do not have another solution. This is the first time in 5 years that there's been a breaking change to VS Code that's stopped Quokka from working, but it is outside of our control and we don't have the ability to fix old versions. If you choose not to renew and want to use the older version then unfortunately it also means you won't be able to use the latest version of VS Code because of their breaking change.

**Comment by russgooday** [comment]
Thank you, that clears that up.
